// HT66F70A.h
//	This file contains the definition of registers for
//		Holtek HT66F70A microcontroller.
//	Generated by cfg2gcch V1.07.
//	[VERSION] 3.2, 4

//	Do not modify manually.

#ifndef _HOLTEK_H_
#define _HOLTEK_H_

#ifndef __DISABLE_HGCC_BUILD_IN__
#include "build-in.h"
#endif

#define DEFINE_ISR(isr_name, vector) void __attribute((interrupt(vector))) isr_name(void)

#define DEFINE_SFR(sfr_type, sfr, addr) static volatile sfr_type sfr __attribute__ ((at(addr)))

typedef unsigned char __sfr_byte;

typedef struct {
	unsigned char __c : 1;
	unsigned char __ac : 1;
	unsigned char __z : 1;
	unsigned char __ov : 1;
	unsigned char __pdf : 1;
	unsigned char __to : 1;
	unsigned char __cz : 1;
	unsigned char __sc : 1;
} __status_bits;

typedef union {
	__status_bits bits;
	__sfr_byte byte;
} __status_type;

typedef struct {
	unsigned char __bp0 : 1;
	unsigned char __bp1 : 1;
	unsigned char : 6;
} __bp_bits;

typedef union {
	__bp_bits bits;
	__sfr_byte byte;
} __bp_type;

typedef struct {
	unsigned char __pawu0 : 1;
	unsigned char __pawu1 : 1;
	unsigned char __pawu2 : 1;
	unsigned char __pawu3 : 1;
	unsigned char __pawu4 : 1;
	unsigned char __pawu5 : 1;
	unsigned char __pawu6 : 1;
	unsigned char __pawu7 : 1;
} __pawu_bits;

typedef union {
	__pawu_bits bits;
	__sfr_byte byte;
} __pawu_type;

typedef struct {
	unsigned char __papu0 : 1;
	unsigned char __papu1 : 1;
	unsigned char __papu2 : 1;
	unsigned char __papu3 : 1;
	unsigned char __papu4 : 1;
	unsigned char __papu5 : 1;
	unsigned char __papu6 : 1;
	unsigned char __papu7 : 1;
} __papu_bits;

typedef union {
	__papu_bits bits;
	__sfr_byte byte;
} __papu_type;

typedef struct {
	unsigned char __pa0 : 1;
	unsigned char __pa1 : 1;
	unsigned char __pa2 : 1;
	unsigned char __pa3 : 1;
	unsigned char __pa4 : 1;
	unsigned char __pa5 : 1;
	unsigned char __pa6 : 1;
	unsigned char __pa7 : 1;
} __pa_bits;

typedef union {
	__pa_bits bits;
	__sfr_byte byte;
} __pa_type;

typedef struct {
	unsigned char __pac0 : 1;
	unsigned char __pac1 : 1;
	unsigned char __pac2 : 1;
	unsigned char __pac3 : 1;
	unsigned char __pac4 : 1;
	unsigned char __pac5 : 1;
	unsigned char __pac6 : 1;
	unsigned char __pac7 : 1;
} __pac_bits;

typedef union {
	__pac_bits bits;
	__sfr_byte byte;
} __pac_type;

typedef struct {
	unsigned char __pbpu0 : 1;
	unsigned char __pbpu1 : 1;
	unsigned char __pbpu2 : 1;
	unsigned char __pbpu3 : 1;
	unsigned char __pbpu4 : 1;
	unsigned char __pbpu5 : 1;
	unsigned char __pbpu6 : 1;
	unsigned char __pbpu7 : 1;
} __pbpu_bits;

typedef union {
	__pbpu_bits bits;
	__sfr_byte byte;
} __pbpu_type;

typedef struct {
	unsigned char __pb0 : 1;
	unsigned char __pb1 : 1;
	unsigned char __pb2 : 1;
	unsigned char __pb3 : 1;
	unsigned char __pb4 : 1;
	unsigned char __pb5 : 1;
	unsigned char __pb6 : 1;
	unsigned char __pb7 : 1;
} __pb_bits;

typedef union {
	__pb_bits bits;
	__sfr_byte byte;
} __pb_type;

typedef struct {
	unsigned char __pbc0 : 1;
	unsigned char __pbc1 : 1;
	unsigned char __pbc2 : 1;
	unsigned char __pbc3 : 1;
	unsigned char __pbc4 : 1;
	unsigned char __pbc5 : 1;
	unsigned char __pbc6 : 1;
	unsigned char __pbc7 : 1;
} __pbc_bits;

typedef union {
	__pbc_bits bits;
	__sfr_byte byte;
} __pbc_type;

typedef struct {
	unsigned char __pcpu0 : 1;
	unsigned char __pcpu1 : 1;
	unsigned char __pcpu2 : 1;
	unsigned char __pcpu3 : 1;
	unsigned char __pcpu4 : 1;
	unsigned char __pcpu5 : 1;
	unsigned char __pcpu6 : 1;
	unsigned char __pcpu7 : 1;
} __pcpu_bits;

typedef union {
	__pcpu_bits bits;
	__sfr_byte byte;
} __pcpu_type;

typedef struct {
	unsigned char __pc0 : 1;
	unsigned char __pc1 : 1;
	unsigned char __pc2 : 1;
	unsigned char __pc3 : 1;
	unsigned char __pc4 : 1;
	unsigned char __pc5 : 1;
	unsigned char __pc6 : 1;
	unsigned char __pc7 : 1;
} __pc_bits;

typedef union {
	__pc_bits bits;
	__sfr_byte byte;
} __pc_type;

typedef struct {
	unsigned char __pcc0 : 1;
	unsigned char __pcc1 : 1;
	unsigned char __pcc2 : 1;
	unsigned char __pcc3 : 1;
	unsigned char __pcc4 : 1;
	unsigned char __pcc5 : 1;
	unsigned char __pcc6 : 1;
	unsigned char __pcc7 : 1;
} __pcc_bits;

typedef union {
	__pcc_bits bits;
	__sfr_byte byte;
} __pcc_type;

typedef struct {
	unsigned char __pdpu0 : 1;
	unsigned char __pdpu1 : 1;
	unsigned char __pdpu2 : 1;
	unsigned char __pdpu3 : 1;
	unsigned char __pdpu4 : 1;
	unsigned char __pdpu5 : 1;
	unsigned char __pdpu6 : 1;
	unsigned char __pdpu7 : 1;
} __pdpu_bits;

typedef union {
	__pdpu_bits bits;
	__sfr_byte byte;
} __pdpu_type;

typedef struct {
	unsigned char __pd0 : 1;
	unsigned char __pd1 : 1;
	unsigned char __pd2 : 1;
	unsigned char __pd3 : 1;
	unsigned char __pd4 : 1;
	unsigned char __pd5 : 1;
	unsigned char __pd6 : 1;
	unsigned char __pd7 : 1;
} __pd_bits;

typedef union {
	__pd_bits bits;
	__sfr_byte byte;
} __pd_type;

typedef struct {
	unsigned char __pdc0 : 1;
	unsigned char __pdc1 : 1;
	unsigned char __pdc2 : 1;
	unsigned char __pdc3 : 1;
	unsigned char __pdc4 : 1;
	unsigned char __pdc5 : 1;
	unsigned char __pdc6 : 1;
	unsigned char __pdc7 : 1;
} __pdc_bits;

typedef union {
	__pdc_bits bits;
	__sfr_byte byte;
} __pdc_type;

typedef struct {
	unsigned char __pepu0 : 1;
	unsigned char __pepu1 : 1;
	unsigned char __pepu2 : 1;
	unsigned char __pepu3 : 1;
	unsigned char __pepu4 : 1;
	unsigned char __pepu5 : 1;
	unsigned char __pepu6 : 1;
	unsigned char __pepu7 : 1;
} __pepu_bits;

typedef union {
	__pepu_bits bits;
	__sfr_byte byte;
} __pepu_type;

typedef struct {
	unsigned char __pe0 : 1;
	unsigned char __pe1 : 1;
	unsigned char __pe2 : 1;
	unsigned char __pe3 : 1;
	unsigned char __pe4 : 1;
	unsigned char __pe5 : 1;
	unsigned char __pe6 : 1;
	unsigned char __pe7 : 1;
} __pe_bits;

typedef union {
	__pe_bits bits;
	__sfr_byte byte;
} __pe_type;

typedef struct {
	unsigned char __pec0 : 1;
	unsigned char __pec1 : 1;
	unsigned char __pec2 : 1;
	unsigned char __pec3 : 1;
	unsigned char __pec4 : 1;
	unsigned char __pec5 : 1;
	unsigned char __pec6 : 1;
	unsigned char __pec7 : 1;
} __pec_bits;

typedef union {
	__pec_bits bits;
	__sfr_byte byte;
} __pec_type;

typedef struct {
	unsigned char __pfpu0 : 1;
	unsigned char __pfpu1 : 1;
	unsigned char __pfpu2 : 1;
	unsigned char __pfpu3 : 1;
	unsigned char __pfpu4 : 1;
	unsigned char __pfpu5 : 1;
	unsigned char __pfpu6 : 1;
	unsigned char : 1;
} __pfpu_bits;

typedef union {
	__pfpu_bits bits;
	__sfr_byte byte;
} __pfpu_type;

typedef struct {
	unsigned char __pf0 : 1;
	unsigned char __pf1 : 1;
	unsigned char __pf2 : 1;
	unsigned char __pf3 : 1;
	unsigned char __pf4 : 1;
	unsigned char __pf5 : 1;
	unsigned char __pf6 : 1;
	unsigned char : 1;
} __pf_bits;

typedef union {
	__pf_bits bits;
	__sfr_byte byte;
} __pf_type;

typedef struct {
	unsigned char __pfc0 : 1;
	unsigned char __pfc1 : 1;
	unsigned char __pfc2 : 1;
	unsigned char __pfc3 : 1;
	unsigned char __pfc4 : 1;
	unsigned char __pfc5 : 1;
	unsigned char __pfc6 : 1;
	unsigned char : 1;
} __pfc_bits;

typedef union {
	__pfc_bits bits;
	__sfr_byte byte;
} __pfc_type;

typedef struct {
	unsigned char __pgpu0 : 1;
	unsigned char __pgpu1 : 1;
	unsigned char __pgpu2 : 1;
	unsigned char __pgpu3 : 1;
	unsigned char __pgpu4 : 1;
	unsigned char __pgpu5 : 1;
	unsigned char __pgpu6 : 1;
	unsigned char __pgpu7 : 1;
} __pgpu_bits;

typedef union {
	__pgpu_bits bits;
	__sfr_byte byte;
} __pgpu_type;

typedef struct {
	unsigned char __pg0 : 1;
	unsigned char __pg1 : 1;
	unsigned char __pg2 : 1;
	unsigned char __pg3 : 1;
	unsigned char __pg4 : 1;
	unsigned char __pg5 : 1;
	unsigned char __pg6 : 1;
	unsigned char __pg7 : 1;
} __pg_bits;

typedef union {
	__pg_bits bits;
	__sfr_byte byte;
} __pg_type;

typedef struct {
	unsigned char __pgc0 : 1;
	unsigned char __pgc1 : 1;
	unsigned char __pgc2 : 1;
	unsigned char __pgc3 : 1;
	unsigned char __pgc4 : 1;
	unsigned char __pgc5 : 1;
	unsigned char __pgc6 : 1;
	unsigned char __pgc7 : 1;
} __pgc_bits;

typedef union {
	__pgc_bits bits;
	__sfr_byte byte;
} __pgc_type;

typedef struct {
	unsigned char __phpu0 : 1;
	unsigned char __phpu1 : 1;
	unsigned char __phpu2 : 1;
	unsigned char __phpu3 : 1;
	unsigned char __phpu4 : 1;
	unsigned char __phpu5 : 1;
	unsigned char : 2;
} __phpu_bits;

typedef union {
	__phpu_bits bits;
	__sfr_byte byte;
} __phpu_type;

typedef struct {
	unsigned char __ph0 : 1;
	unsigned char __ph1 : 1;
	unsigned char __ph2 : 1;
	unsigned char __ph3 : 1;
	unsigned char __ph4 : 1;
	unsigned char __ph5 : 1;
	unsigned char : 2;
} __ph_bits;

typedef union {
	__ph_bits bits;
	__sfr_byte byte;
} __ph_type;

typedef struct {
	unsigned char __phc0 : 1;
	unsigned char __phc1 : 1;
	unsigned char __phc2 : 1;
	unsigned char __phc3 : 1;
	unsigned char __phc4 : 1;
	unsigned char __phc5 : 1;
	unsigned char : 2;
} __phc_bits;

typedef union {
	__phc_bits bits;
	__sfr_byte byte;
} __phc_type;

typedef struct {
	unsigned char __emi : 1;
	unsigned char __int0e : 1;
	unsigned char __int1e : 1;
	unsigned char __cp0e : 1;
	unsigned char __int0f : 1;
	unsigned char __int1f : 1;
	unsigned char __cp0f : 1;
	unsigned char : 1;
} __intc0_bits;

typedef union {
	__intc0_bits bits;
	__sfr_byte byte;
} __intc0_type;

typedef struct {
	unsigned char __cp1e : 1;
	unsigned char __mf0e : 1;
	unsigned char __mf1e : 1;
	unsigned char __ade : 1;
	unsigned char __cp1f : 1;
	unsigned char __mf0f : 1;
	unsigned char __mf1f : 1;
	unsigned char __adf : 1;
} __intc1_bits;

typedef union {
	__intc1_bits bits;
	__sfr_byte byte;
} __intc1_type;

typedef struct {
	unsigned char __mf2e : 1;
	unsigned char __tb0e : 1;
	unsigned char __tb1e : 1;
	unsigned char __mf3e : 1;
	unsigned char __mf2f : 1;
	unsigned char __tb0f : 1;
	unsigned char __tb1f : 1;
	unsigned char __mf3f : 1;
} __intc2_bits;

typedef union {
	__intc2_bits bits;
	__sfr_byte byte;
} __intc2_type;

typedef struct {
	unsigned char __int2e : 1;
	unsigned char __int3e : 1;
	unsigned char __mf4e : 1;
	unsigned char : 1;
	unsigned char __int2f : 1;
	unsigned char __int3f : 1;
	unsigned char __mf4f : 1;
	unsigned char : 1;
} __intc3_bits;

typedef union {
	__intc3_bits bits;
	__sfr_byte byte;
} __intc3_type;

typedef struct {
	unsigned char __t0pe : 1;
	unsigned char __t0ae : 1;
	unsigned char __t2pe : 1;
	unsigned char __t2ae : 1;
	unsigned char __t0pf : 1;
	unsigned char __t0af : 1;
	unsigned char __t2pf : 1;
	unsigned char __t2af : 1;
} __mfi0_bits;

typedef union {
	__mfi0_bits bits;
	__sfr_byte byte;
} __mfi0_type;

typedef struct {
	unsigned char __t1pe : 1;
	unsigned char __t1ae : 1;
	unsigned char __t1be : 1;
	unsigned char : 1;
	unsigned char __t1pf : 1;
	unsigned char __t1af : 1;
	unsigned char __t1bf : 1;
	unsigned char : 1;
} __mfi1_bits;

typedef union {
	__mfi1_bits bits;
	__sfr_byte byte;
} __mfi1_type;

typedef struct {
	unsigned char __xpe : 1;
	unsigned char __t3pe : 1;
	unsigned char __t3ae : 1;
	unsigned char __sime : 1;
	unsigned char __xpf : 1;
	unsigned char __t3pf : 1;
	unsigned char __t3af : 1;
	unsigned char __simf : 1;
} __mfi2_bits;

typedef union {
	__mfi2_bits bits;
	__sfr_byte byte;
} __mfi2_type;

typedef struct {
	unsigned char : 1;
	unsigned char __lve : 1;
	unsigned char __dee : 1;
	unsigned char __spiae : 1;
	unsigned char : 1;
	unsigned char __lvf : 1;
	unsigned char __def : 1;
	unsigned char __spiaf : 1;
} __mfi3_bits;

typedef union {
	__mfi3_bits bits;
	__sfr_byte byte;
} __mfi3_type;

typedef struct {
	unsigned char __t4pe : 1;
	unsigned char __t4ae : 1;
	unsigned char __t5pe : 1;
	unsigned char __t5ae : 1;
	unsigned char __t4pf : 1;
	unsigned char __t4af : 1;
	unsigned char __t5pf : 1;
	unsigned char __t5af : 1;
} __mfi4_bits;

typedef union {
	__mfi4_bits bits;
	__sfr_byte byte;
} __mfi4_type;

typedef struct {
	unsigned char __int0s0 : 1;
	unsigned char __int0s1 : 1;
	unsigned char __int1s0 : 1;
	unsigned char __int1s1 : 1;
	unsigned char __int2s0 : 1;
	unsigned char __int2s1 : 1;
	unsigned char __int3s0 : 1;
	unsigned char __int3s1 : 1;
} __integ_bits;

typedef union {
	__integ_bits bits;
	__sfr_byte byte;
} __integ_type;

typedef struct {
	unsigned char __hlclk : 1;
	unsigned char __idlen : 1;
	unsigned char __hto : 1;
	unsigned char __lto : 1;
	unsigned char __fsten : 1;
	unsigned char __cks0 : 1;
	unsigned char __cks1 : 1;
	unsigned char __cks2 : 1;
} __smod_bits;

typedef union {
	__smod_bits bits;
	__sfr_byte byte;
} __smod_type;

typedef struct {
	unsigned char __wrf : 1;
	unsigned char __lrf : 1;
	unsigned char __lvrf : 1;
	unsigned char : 4;
	unsigned char __fsyson : 1;
} __smod1_bits;

typedef union {
	__smod1_bits bits;
	__sfr_byte byte;
} __smod1_type;

typedef struct {
	unsigned char __lvs0 : 1;
	unsigned char __lvs1 : 1;
	unsigned char __lvs2 : 1;
	unsigned char __lvs3 : 1;
	unsigned char __lvs4 : 1;
	unsigned char __lvs5 : 1;
	unsigned char __lvs6 : 1;
	unsigned char __lvs7 : 1;
} __lvrc_bits;

typedef union {
	__lvrc_bits bits;
	__sfr_byte byte;
} __lvrc_type;

typedef struct {
	unsigned char __vlvd0 : 1;
	unsigned char __vlvd1 : 1;
	unsigned char __vlvd2 : 1;
	unsigned char : 1;
	unsigned char __lvden : 1;
	unsigned char __lvdo : 1;
	unsigned char : 2;
} __lvdc_bits;

typedef union {
	__lvdc_bits bits;
	__sfr_byte byte;
} __lvdc_type;

typedef struct {
	unsigned char __ws0 : 1;
	unsigned char __ws1 : 1;
	unsigned char __ws2 : 1;
	unsigned char __we0 : 1;
	unsigned char __we1 : 1;
	unsigned char __we2 : 1;
	unsigned char __we3 : 1;
	unsigned char __we4 : 1;
} __wdtc_bits;

typedef union {
	__wdtc_bits bits;
	__sfr_byte byte;
} __wdtc_type;

typedef struct {
	unsigned char __lxtlp : 1;
	unsigned char : 7;
} __smod2_bits;

typedef union {
	__smod2_bits bits;
	__sfr_byte byte;
} __smod2_type;

typedef struct {
	unsigned char __c0hyen : 1;
	unsigned char : 3;
	unsigned char __c0out : 1;
	unsigned char __c0pol : 1;
	unsigned char __c0en : 1;
	unsigned char : 1;
} __cp0c_bits;

typedef union {
	__cp0c_bits bits;
	__sfr_byte byte;
} __cp0c_type;

typedef struct {
	unsigned char __c1hyen : 1;
	unsigned char : 3;
	unsigned char __c1out : 1;
	unsigned char __c1pol : 1;
	unsigned char __c1en : 1;
	unsigned char : 1;
} __cp1c_bits;

typedef union {
	__cp1c_bits bits;
	__sfr_byte byte;
} __cp1c_type;

typedef struct {
	unsigned char __t1rp0 : 1;
	unsigned char __t1rp1 : 1;
	unsigned char __t1rp2 : 1;
	unsigned char __t1on : 1;
	unsigned char __t1ck0 : 1;
	unsigned char __t1ck1 : 1;
	unsigned char __t1ck2 : 1;
	unsigned char __t1pau : 1;
} __tm1c0_bits;

typedef union {
	__tm1c0_bits bits;
	__sfr_byte byte;
} __tm1c0_type;

typedef struct {
	unsigned char __t1cclr : 1;
	unsigned char __t1cdn : 1;
	unsigned char __t1apol : 1;
	unsigned char __t1aoc : 1;
	unsigned char __t1aio0 : 1;
	unsigned char __t1aio1 : 1;
	unsigned char __t1am0 : 1;
	unsigned char __t1am1 : 1;
} __tm1c1_bits;

typedef union {
	__tm1c1_bits bits;
	__sfr_byte byte;
} __tm1c1_type;

typedef struct {
	unsigned char __t1pwm0 : 1;
	unsigned char __t1pwm1 : 1;
	unsigned char __t1bpol : 1;
	unsigned char __t1boc : 1;
	unsigned char __t1bio0 : 1;
	unsigned char __t1bio1 : 1;
	unsigned char __t1bm0 : 1;
	unsigned char __t1bm1 : 1;
} __tm1c2_bits;

typedef union {
	__tm1c2_bits bits;
	__sfr_byte byte;
} __tm1c2_type;

typedef struct {
	unsigned char : 3;
	unsigned char __t2on : 1;
	unsigned char __t2ck0 : 1;
	unsigned char __t2ck1 : 1;
	unsigned char __t2ck2 : 1;
	unsigned char __t2pau : 1;
} __tm2c0_bits;

typedef union {
	__tm2c0_bits bits;
	__sfr_byte byte;
} __tm2c0_type;

typedef struct {
	unsigned char __t2cclr : 1;
	unsigned char __t2dpx : 1;
	unsigned char __t2pol : 1;
	unsigned char __t2oc : 1;
	unsigned char __t2io0 : 1;
	unsigned char __t2io1 : 1;
	unsigned char __t2m0 : 1;
	unsigned char __t2m1 : 1;
} __tm2c1_bits;

typedef union {
	__tm2c1_bits bits;
	__sfr_byte byte;
} __tm2c1_type;

typedef struct {
	unsigned char __t3rp0 : 1;
	unsigned char __t3rp1 : 1;
	unsigned char __t3rp2 : 1;
	unsigned char __t3on : 1;
	unsigned char __t3ck0 : 1;
	unsigned char __t3ck1 : 1;
	unsigned char __t3ck2 : 1;
	unsigned char __t3pau : 1;
} __tm3c0_bits;

typedef union {
	__tm3c0_bits bits;
	__sfr_byte byte;
} __tm3c0_type;

typedef struct {
	unsigned char __t3cclr : 1;
	unsigned char __t3dpx : 1;
	unsigned char __t3pol : 1;
	unsigned char __t3oc : 1;
	unsigned char __t3io0 : 1;
	unsigned char __t3io1 : 1;
	unsigned char __t3m0 : 1;
	unsigned char __t3m1 : 1;
} __tm3c1_bits;

typedef union {
	__tm3c1_bits bits;
	__sfr_byte byte;
} __tm3c1_type;

typedef struct {
	unsigned char __t0rp0 : 1;
	unsigned char __t0rp1 : 1;
	unsigned char __t0rp2 : 1;
	unsigned char __t0on : 1;
	unsigned char __t0ck0 : 1;
	unsigned char __t0ck1 : 1;
	unsigned char __t0ck2 : 1;
	unsigned char __t0pau : 1;
} __tm0c0_bits;

typedef union {
	__tm0c0_bits bits;
	__sfr_byte byte;
} __tm0c0_type;

typedef struct {
	unsigned char __t0cclr : 1;
	unsigned char __t0dpx : 1;
	unsigned char __t0pol : 1;
	unsigned char __t0oc : 1;
	unsigned char __t0io0 : 1;
	unsigned char __t0io1 : 1;
	unsigned char __t0m0 : 1;
	unsigned char __t0m1 : 1;
} __tm0c1_bits;

typedef union {
	__tm0c1_bits bits;
	__sfr_byte byte;
} __tm0c1_type;

typedef struct {
	unsigned char __clks00 : 1;
	unsigned char __clks01 : 1;
	unsigned char : 6;
} __psc0_bits;

typedef union {
	__psc0_bits bits;
	__sfr_byte byte;
} __psc0_type;

typedef struct {
	unsigned char __tb00 : 1;
	unsigned char __tb01 : 1;
	unsigned char __tb02 : 1;
	unsigned char : 4;
	unsigned char __tb0on : 1;
} __tbc0_bits;

typedef union {
	__tbc0_bits bits;
	__sfr_byte byte;
} __tbc0_type;

typedef struct {
	unsigned char __tb10 : 1;
	unsigned char __tb11 : 1;
	unsigned char __tb12 : 1;
	unsigned char : 4;
	unsigned char __tb1on : 1;
} __tbc1_bits;

typedef union {
	__tbc1_bits bits;
	__sfr_byte byte;
} __tbc1_type;

typedef struct {
	unsigned char __clks10 : 1;
	unsigned char __clks11 : 1;
	unsigned char : 6;
} __psc1_bits;

typedef union {
	__psc1_bits bits;
	__sfr_byte byte;
} __psc1_type;

typedef struct {
	unsigned char __acs0 : 1;
	unsigned char __acs1 : 1;
	unsigned char __acs2 : 1;
	unsigned char __acs3 : 1;
	unsigned char __acs4 : 1;
	unsigned char __adoff : 1;
	unsigned char __eocb : 1;
	unsigned char __start : 1;
} __adcr0_bits;

typedef union {
	__adcr0_bits bits;
	__sfr_byte byte;
} __adcr0_type;

typedef struct {
	unsigned char __adck0 : 1;
	unsigned char __adck1 : 1;
	unsigned char __adck2 : 1;
	unsigned char : 1;
	unsigned char __vrefs : 1;
	unsigned char __adrfs : 1;
	unsigned char __vbgen : 1;
	unsigned char : 1;
} __adcr1_bits;

typedef union {
	__adcr1_bits bits;
	__sfr_byte byte;
} __adcr1_type;

typedef struct {
	unsigned char : 1;
	unsigned char __simen : 1;
	unsigned char __simdeb0 : 1;
	unsigned char __simdeb1 : 1;
	unsigned char : 1;
	unsigned char __sim0 : 1;
	unsigned char __sim1 : 1;
	unsigned char __sim2 : 1;
} __simc0_bits;

typedef union {
	__simc0_bits bits;
	__sfr_byte byte;
} __simc0_type;

typedef struct {
	unsigned char __rxak : 1;
	unsigned char __iamwu : 1;
	unsigned char __srw : 1;
	unsigned char __txak : 1;
	unsigned char __htx : 1;
	unsigned char __hbb : 1;
	unsigned char __haas : 1;
	unsigned char __hcf : 1;
} __simc1_bits;

typedef union {
	__simc1_bits bits;
	__sfr_byte byte;
} __simc1_type;

typedef struct {
	unsigned char __trf : 1;
	unsigned char __wcol : 1;
	unsigned char __csen : 1;
	unsigned char __mls : 1;
	unsigned char __ckeg : 1;
	unsigned char __ckpolb : 1;
	unsigned char : 2;
} __simc2_bits;

typedef union {
	__simc2_bits bits;
	__sfr_byte byte;
} __simc2_type;

typedef struct {
	unsigned char : 1;
	unsigned char __iica0 : 1;
	unsigned char __iica1 : 1;
	unsigned char __iica2 : 1;
	unsigned char __iica3 : 1;
	unsigned char __iica4 : 1;
	unsigned char __iica5 : 1;
	unsigned char __iica6 : 1;
} __sima_bits;

typedef union {
	__sima_bits bits;
	__sfr_byte byte;
} __sima_type;

typedef struct {
	unsigned char __i2ctos0 : 1;
	unsigned char __i2ctos1 : 1;
	unsigned char __i2ctos2 : 1;
	unsigned char __i2ctos3 : 1;
	unsigned char __i2ctos4 : 1;
	unsigned char __i2ctos5 : 1;
	unsigned char __i2ctof : 1;
	unsigned char __i2ctoen : 1;
} __i2ctoc_bits;

typedef union {
	__i2ctoc_bits bits;
	__sfr_byte byte;
} __i2ctoc_type;

typedef struct {
	unsigned char : 1;
	unsigned char __spiaen : 1;
	unsigned char : 3;
	unsigned char __saspi0 : 1;
	unsigned char __saspi1 : 1;
	unsigned char __saspi2 : 1;
} __spiac0_bits;

typedef union {
	__spiac0_bits bits;
	__sfr_byte byte;
} __spiac0_type;

typedef struct {
	unsigned char __satrf : 1;
	unsigned char __sawcol : 1;
	unsigned char __sacsen : 1;
	unsigned char __samls : 1;
	unsigned char __sackeg : 1;
	unsigned char __sackpol : 1;
	unsigned char : 2;
} __spiac1_bits;

typedef union {
	__spiac1_bits bits;
	__sfr_byte byte;
} __spiac1_type;

typedef struct {
	unsigned char __a0 : 1;
	unsigned char __a1 : 1;
	unsigned char __a2 : 1;
	unsigned char __a3 : 1;
	unsigned char __a4 : 1;
	unsigned char __a5 : 1;
	unsigned char __a6 : 1;
	unsigned char __a7 : 1;
} __farl_bits;

typedef union {
	__farl_bits bits;
	__sfr_byte byte;
} __farl_type;

typedef struct {
	unsigned char __a8 : 1;
	unsigned char __a9 : 1;
	unsigned char __a10 : 1;
	unsigned char __a11 : 1;
	unsigned char __a12 : 1;
	unsigned char __a13 : 1;
	unsigned char __a14 : 1;
	unsigned char : 1;
} __farh_bits;

typedef union {
	__farh_bits bits;
	__sfr_byte byte;
} __farh_type;

typedef struct {
	unsigned char __tb20 : 1;
	unsigned char __tb21 : 1;
	unsigned char __tb22 : 1;
	unsigned char : 4;
	unsigned char __tb2en : 1;
} __tbc2_bits;

typedef union {
	__tbc2_bits bits;
	__sfr_byte byte;
} __tbc2_type;

typedef struct {
	unsigned char : 4;
	unsigned char __scomen : 1;
	unsigned char __isel0 : 1;
	unsigned char __isel1 : 1;
	unsigned char : 1;
} __scomc_bits;

typedef union {
	__scomc_bits bits;
	__sfr_byte byte;
} __scomc_type;

typedef struct {
	unsigned char __rd : 1;
	unsigned char __rden : 1;
	unsigned char __wr : 1;
	unsigned char __wren : 1;
	unsigned char : 4;
} __eec_bits;

typedef union {
	__eec_bits bits;
	__sfr_byte byte;
} __eec_type;

typedef struct {
	unsigned char __frd : 1;
	unsigned char __frden : 1;
	unsigned char __fwt : 1;
	unsigned char __fwpen : 1;
	unsigned char __fmod0 : 1;
	unsigned char __fmod1 : 1;
	unsigned char __fmod2 : 1;
	unsigned char __cfwen : 1;
} __fc0_bits;

typedef union {
	__fc0_bits bits;
	__sfr_byte byte;
} __fc0_type;

typedef struct {
	unsigned char __clwb : 1;
	unsigned char : 7;
} __fc2_bits;

typedef union {
	__fc2_bits bits;
	__sfr_byte byte;
} __fc2_type;

typedef struct {
	unsigned char __int0s0 : 1;
	unsigned char __int0s1 : 1;
	unsigned char __int1s0 : 1;
	unsigned char __int1s1 : 1;
	unsigned char __int2s0 : 1;
	unsigned char __int2s1 : 1;
	unsigned char __pintbs0 : 1;
	unsigned char __pintbs1 : 1;
} __ifs0_bits;

typedef union {
	__ifs0_bits bits;
	__sfr_byte byte;
} __ifs0_type;

typedef struct {
	unsigned char __tck0s0 : 1;
	unsigned char __tck0s1 : 1;
	unsigned char __tck1s0 : 1;
	unsigned char __tck1s1 : 1;
	unsigned char __tck2s0 : 1;
	unsigned char __tck2s1 : 1;
	unsigned char __tck3s0 : 1;
	unsigned char __tck3s1 : 1;
} __ifs1_bits;

typedef union {
	__ifs1_bits bits;
	__sfr_byte byte;
} __ifs1_type;

typedef struct {
	unsigned char : 2;
	unsigned char __tpi1as0 : 1;
	unsigned char __tpi1as1 : 1;
	unsigned char __tpi1bs0 : 1;
	unsigned char __tpi1bs1 : 1;
	unsigned char __tpi2s0 : 1;
	unsigned char __tpi2s1 : 1;
} __ifs2_bits;

typedef union {
	__ifs2_bits bits;
	__sfr_byte byte;
} __ifs2_type;

typedef struct {
	unsigned char : 2;
	unsigned char __tpi4s0 : 1;
	unsigned char __tpi4s1 : 1;
	unsigned char __tpi5s0 : 1;
	unsigned char __tpi5s1 : 1;
	unsigned char : 2;
} __ifs3_bits;

typedef union {
	__ifs3_bits bits;
	__sfr_byte byte;
} __ifs3_type;

typedef struct {
	unsigned char __scsbs0 : 1;
	unsigned char __scsbs1 : 1;
	unsigned char __scks0 : 1;
	unsigned char __scks1 : 1;
	unsigned char __sdis0 : 1;
	unsigned char __sdis1 : 1;
	unsigned char : 2;
} __ifs4_bits;

typedef union {
	__ifs4_bits bits;
	__sfr_byte byte;
} __ifs4_type;

typedef struct {
	unsigned char __scsbas0 : 1;
	unsigned char __scsbas1 : 1;
	unsigned char __sckas0 : 1;
	unsigned char __sckas1 : 1;
	unsigned char __sdias0 : 1;
	unsigned char __sdias1 : 1;
	unsigned char : 2;
} __ifs5_bits;

typedef union {
	__ifs5_bits bits;
	__sfr_byte byte;
} __ifs5_type;

typedef struct {
	unsigned char : 3;
	unsigned char __t4on : 1;
	unsigned char __t4ck0 : 1;
	unsigned char __t4ck1 : 1;
	unsigned char __t4ck2 : 1;
	unsigned char __t4pau : 1;
} __tm4c0_bits;

typedef union {
	__tm4c0_bits bits;
	__sfr_byte byte;
} __tm4c0_type;

typedef struct {
	unsigned char __t4cclr : 1;
	unsigned char __t4dpx : 1;
	unsigned char __t4pol : 1;
	unsigned char __t4oc : 1;
	unsigned char __t4io0 : 1;
	unsigned char __t4io1 : 1;
	unsigned char __t4m0 : 1;
	unsigned char __t4m1 : 1;
} __tm4c1_bits;

typedef union {
	__tm4c1_bits bits;
	__sfr_byte byte;
} __tm4c1_type;

typedef struct {
	unsigned char : 3;
	unsigned char __t5on : 1;
	unsigned char __t5ck0 : 1;
	unsigned char __t5ck1 : 1;
	unsigned char __t5ck2 : 1;
	unsigned char __t5pau : 1;
} __tm5c0_bits;

typedef union {
	__tm5c0_bits bits;
	__sfr_byte byte;
} __tm5c0_type;

typedef struct {
	unsigned char __t5cclr : 1;
	unsigned char __t5dpx : 1;
	unsigned char __t5pol : 1;
	unsigned char __t5oc : 1;
	unsigned char __t5io0 : 1;
	unsigned char __t5io1 : 1;
	unsigned char __t5m0 : 1;
	unsigned char __t5m1 : 1;
} __tm5c1_bits;

typedef union {
	__tm5c1_bits bits;
	__sfr_byte byte;
} __tm5c1_type;

typedef struct {
	unsigned char : 4;
	unsigned char __pa1s0 : 1;
	unsigned char __pa1s1 : 1;
	unsigned char __pa1s2 : 1;
	unsigned char __pa1s3 : 1;
} __pas0_bits;

typedef union {
	__pas0_bits bits;
	__sfr_byte byte;
} __pas0_type;

typedef struct {
	unsigned char : 4;
	unsigned char __pa3s0 : 1;
	unsigned char __pa3s1 : 1;
	unsigned char __pa3s2 : 1;
	unsigned char __pa3s3 : 1;
} __pas1_bits;

typedef union {
	__pas1_bits bits;
	__sfr_byte byte;
} __pas1_type;

typedef struct {
	unsigned char __pa4s0 : 1;
	unsigned char __pa4s1 : 1;
	unsigned char __pa4s2 : 1;
	unsigned char __pa4s3 : 1;
	unsigned char __pa5s0 : 1;
	unsigned char __pa5s1 : 1;
	unsigned char __pa5s2 : 1;
	unsigned char __pa5s3 : 1;
} __pas2_bits;

typedef union {
	__pas2_bits bits;
	__sfr_byte byte;
} __pas2_type;

typedef struct {
	unsigned char __pa6s0 : 1;
	unsigned char __pa6s1 : 1;
	unsigned char __pa6s2 : 1;
	unsigned char __pa6s3 : 1;
	unsigned char __pa7s0 : 1;
	unsigned char __pa7s1 : 1;
	unsigned char __pa7s2 : 1;
	unsigned char __pa7s3 : 1;
} __pas3_bits;

typedef union {
	__pas3_bits bits;
	__sfr_byte byte;
} __pas3_type;

typedef struct {
	unsigned char : 4;
	unsigned char __pb5s0 : 1;
	unsigned char __pb5s1 : 1;
	unsigned char __pb5s2 : 1;
	unsigned char __pb5s3 : 1;
} __pbs2_bits;

typedef union {
	__pbs2_bits bits;
	__sfr_byte byte;
} __pbs2_type;

typedef struct {
	unsigned char __pb6s0 : 1;
	unsigned char __pb6s1 : 1;
	unsigned char __pb6s2 : 1;
	unsigned char __pb6s3 : 1;
	unsigned char __pb7s0 : 1;
	unsigned char __pb7s1 : 1;
	unsigned char __pb7s2 : 1;
	unsigned char __pb7s3 : 1;
} __pbs3_bits;

typedef union {
	__pbs3_bits bits;
	__sfr_byte byte;
} __pbs3_type;

typedef struct {
	unsigned char __pc0s0 : 1;
	unsigned char __pc0s1 : 1;
	unsigned char __pc0s2 : 1;
	unsigned char __pc0s3 : 1;
	unsigned char __pc1s0 : 1;
	unsigned char __pc1s1 : 1;
	unsigned char __pc1s2 : 1;
	unsigned char __pc1s3 : 1;
} __pcs0_bits;

typedef union {
	__pcs0_bits bits;
	__sfr_byte byte;
} __pcs0_type;

typedef struct {
	unsigned char __pc2s0 : 1;
	unsigned char __pc2s1 : 1;
	unsigned char __pc2s2 : 1;
	unsigned char __pc2s3 : 1;
	unsigned char __pc3s0 : 1;
	unsigned char __pc3s1 : 1;
	unsigned char __pc3s2 : 1;
	unsigned char __pc3s3 : 1;
} __pcs1_bits;

typedef union {
	__pcs1_bits bits;
	__sfr_byte byte;
} __pcs1_type;

typedef struct {
	unsigned char __pc4s0 : 1;
	unsigned char __pc4s1 : 1;
	unsigned char __pc4s2 : 1;
	unsigned char __pc4s3 : 1;
	unsigned char __pc5s0 : 1;
	unsigned char __pc5s1 : 1;
	unsigned char __pc5s2 : 1;
	unsigned char __pc5s3 : 1;
} __pcs2_bits;

typedef union {
	__pcs2_bits bits;
	__sfr_byte byte;
} __pcs2_type;

typedef struct {
	unsigned char __pc6s0 : 1;
	unsigned char __pc6s1 : 1;
	unsigned char __pc6s2 : 1;
	unsigned char __pc6s3 : 1;
	unsigned char __pc7s0 : 1;
	unsigned char __pc7s1 : 1;
	unsigned char __pc7s2 : 1;
	unsigned char __pc7s3 : 1;
} __pcs3_bits;

typedef union {
	__pcs3_bits bits;
	__sfr_byte byte;
} __pcs3_type;

typedef struct {
	unsigned char __pd0s0 : 1;
	unsigned char __pd0s1 : 1;
	unsigned char __pd0s2 : 1;
	unsigned char __pd0s3 : 1;
	unsigned char __pd1s0 : 1;
	unsigned char __pd1s1 : 1;
	unsigned char __pd1s2 : 1;
	unsigned char __pd1s3 : 1;
} __pds0_bits;

typedef union {
	__pds0_bits bits;
	__sfr_byte byte;
} __pds0_type;

typedef struct {
	unsigned char __pd2s0 : 1;
	unsigned char __pd2s1 : 1;
	unsigned char __pd2s2 : 1;
	unsigned char __pd2s3 : 1;
	unsigned char __pd3s0 : 1;
	unsigned char __pd3s1 : 1;
	unsigned char __pd3s2 : 1;
	unsigned char __pd3s3 : 1;
} __pds1_bits;

typedef union {
	__pds1_bits bits;
	__sfr_byte byte;
} __pds1_type;

typedef struct {
	unsigned char __pd4s0 : 1;
	unsigned char __pd4s1 : 1;
	unsigned char __pd4s2 : 1;
	unsigned char __pd4s3 : 1;
	unsigned char __pd5s0 : 1;
	unsigned char __pd5s1 : 1;
	unsigned char __pd5s2 : 1;
	unsigned char __pd5s3 : 1;
} __pds2_bits;

typedef union {
	__pds2_bits bits;
	__sfr_byte byte;
} __pds2_type;

typedef struct {
	unsigned char __pd6s0 : 1;
	unsigned char __pd6s1 : 1;
	unsigned char __pd6s2 : 1;
	unsigned char __pd6s3 : 1;
	unsigned char __pd7s0 : 1;
	unsigned char __pd7s1 : 1;
	unsigned char __pd7s2 : 1;
	unsigned char __pd7s3 : 1;
} __pds3_bits;

typedef union {
	__pds3_bits bits;
	__sfr_byte byte;
} __pds3_type;

typedef struct {
	unsigned char __pe0s0 : 1;
	unsigned char __pe0s1 : 1;
	unsigned char __pe0s2 : 1;
	unsigned char __pe0s3 : 1;
	unsigned char __pe1s0 : 1;
	unsigned char __pe1s1 : 1;
	unsigned char __pe1s2 : 1;
	unsigned char __pe1s3 : 1;
} __pes0_bits;

typedef union {
	__pes0_bits bits;
	__sfr_byte byte;
} __pes0_type;

typedef struct {
	unsigned char : 4;
	unsigned char __pe3s0 : 1;
	unsigned char __pe3s1 : 1;
	unsigned char __pe3s2 : 1;
	unsigned char __pe3s3 : 1;
} __pes1_bits;

typedef union {
	__pes1_bits bits;
	__sfr_byte byte;
} __pes1_type;

typedef struct {
	unsigned char __pe4s0 : 1;
	unsigned char __pe4s1 : 1;
	unsigned char __pe4s2 : 1;
	unsigned char __pe4s3 : 1;
	unsigned char __pe5s0 : 1;
	unsigned char __pe5s1 : 1;
	unsigned char __pe5s2 : 1;
	unsigned char __pe5s3 : 1;
} __pes2_bits;

typedef union {
	__pes2_bits bits;
	__sfr_byte byte;
} __pes2_type;

typedef struct {
	unsigned char __pe6s0 : 1;
	unsigned char __pe6s1 : 1;
	unsigned char __pe6s2 : 1;
	unsigned char __pe6s3 : 1;
	unsigned char __pe7s0 : 1;
	unsigned char __pe7s1 : 1;
	unsigned char __pe7s2 : 1;
	unsigned char __pe7s3 : 1;
} __pes3_bits;

typedef union {
	__pes3_bits bits;
	__sfr_byte byte;
} __pes3_type;

typedef struct {
	unsigned char __pf0s0 : 1;
	unsigned char __pf0s1 : 1;
	unsigned char __pf0s2 : 1;
	unsigned char __pf0s3 : 1;
	unsigned char __pf1s0 : 1;
	unsigned char __pf1s1 : 1;
	unsigned char __pf1s2 : 1;
	unsigned char __pf1s3 : 1;
} __pfs0_bits;

typedef union {
	__pfs0_bits bits;
	__sfr_byte byte;
} __pfs0_type;

typedef struct {
	unsigned char __pg0s0 : 1;
	unsigned char __pg0s1 : 1;
	unsigned char __pg0s2 : 1;
	unsigned char __pg0s3 : 1;
	unsigned char __pg1s0 : 1;
	unsigned char __pg1s1 : 1;
	unsigned char __pg1s2 : 1;
	unsigned char __pg1s3 : 1;
} __pgs0_bits;

typedef union {
	__pgs0_bits bits;
	__sfr_byte byte;
} __pgs0_type;

typedef struct {
	unsigned char : 4;
	unsigned char __pg3s0 : 1;
	unsigned char __pg3s1 : 1;
	unsigned char __pg3s2 : 1;
	unsigned char __pg3s3 : 1;
} __pgs1_bits;

typedef union {
	__pgs1_bits bits;
	__sfr_byte byte;
} __pgs1_type;

typedef struct {
	unsigned char __pg4s0 : 1;
	unsigned char __pg4s1 : 1;
	unsigned char __pg4s2 : 1;
	unsigned char __pg4s3 : 1;
	unsigned char : 4;
} __pgs2_bits;

typedef union {
	__pgs2_bits bits;
	__sfr_byte byte;
} __pgs2_type;

typedef struct {
	unsigned char __pg6s0 : 1;
	unsigned char __pg6s1 : 1;
	unsigned char __pg6s2 : 1;
	unsigned char __pg6s3 : 1;
	unsigned char __pg7s0 : 1;
	unsigned char __pg7s1 : 1;
	unsigned char __pg7s2 : 1;
	unsigned char __pg7s3 : 1;
} __pgs3_bits;

typedef union {
	__pgs3_bits bits;
	__sfr_byte byte;
} __pgs3_type;

typedef struct {
	unsigned char __ph0s0 : 1;
	unsigned char __ph0s1 : 1;
	unsigned char __ph0s2 : 1;
	unsigned char __ph0s3 : 1;
	unsigned char __ph1s0 : 1;
	unsigned char __ph1s1 : 1;
	unsigned char __ph1s2 : 1;
	unsigned char __ph1s3 : 1;
} __phs0_bits;

typedef union {
	__phs0_bits bits;
	__sfr_byte byte;
} __phs0_type;

typedef struct {
	unsigned char __ph2s0 : 1;
	unsigned char __ph2s1 : 1;
	unsigned char __ph2s2 : 1;
	unsigned char __ph2s3 : 1;
	unsigned char __ph3s0 : 1;
	unsigned char __ph3s1 : 1;
	unsigned char __ph3s2 : 1;
	unsigned char __ph3s3 : 1;
} __phs1_bits;

typedef union {
	__phs1_bits bits;
	__sfr_byte byte;
} __phs1_type;

typedef struct {
	unsigned char : 4;
	unsigned char __ph5s0 : 1;
	unsigned char __ph5s1 : 1;
	unsigned char __ph5s2 : 1;
	unsigned char __ph5s3 : 1;
} __phs2_bits;

typedef union {
	__phs2_bits bits;
	__sfr_byte byte;
} __phs2_type;


DEFINE_SFR(__sfr_byte, __mp0, 0x01);
DEFINE_SFR(__sfr_byte, __mp1l, 0x03);
DEFINE_SFR(__sfr_byte, __mp1h, 0x04);
DEFINE_SFR(__sfr_byte, __acc, 0x05);
DEFINE_SFR(__sfr_byte, __pcl, 0x06);
DEFINE_SFR(__sfr_byte, __tblp, 0x07);
DEFINE_SFR(__sfr_byte, __tblh, 0x08);
DEFINE_SFR(__sfr_byte, __tbhp, 0x09);
DEFINE_SFR(__status_type, __status, 0x0a);
DEFINE_SFR(__bp_type, __bp, 0x0b);
DEFINE_SFR(__sfr_byte, __mp2l, 0x0d);
DEFINE_SFR(__sfr_byte, __mp2h, 0x0e);
DEFINE_SFR(__pawu_type, __pawu, 0x10);
DEFINE_SFR(__papu_type, __papu, 0x11);
DEFINE_SFR(__pa_type, __pa, 0x12);
DEFINE_SFR(__pac_type, __pac, 0x13);
DEFINE_SFR(__pbpu_type, __pbpu, 0x15);
DEFINE_SFR(__pb_type, __pb, 0x16);
DEFINE_SFR(__pbc_type, __pbc, 0x17);
DEFINE_SFR(__pcpu_type, __pcpu, 0x19);
DEFINE_SFR(__pc_type, __pc, 0x1a);
DEFINE_SFR(__pcc_type, __pcc, 0x1b);
DEFINE_SFR(__pdpu_type, __pdpu, 0x1d);
DEFINE_SFR(__pd_type, __pd, 0x1e);
DEFINE_SFR(__pdc_type, __pdc, 0x1f);
DEFINE_SFR(__pepu_type, __pepu, 0x21);
DEFINE_SFR(__pe_type, __pe, 0x22);
DEFINE_SFR(__pec_type, __pec, 0x23);
DEFINE_SFR(__pfpu_type, __pfpu, 0x25);
DEFINE_SFR(__pf_type, __pf, 0x26);
DEFINE_SFR(__pfc_type, __pfc, 0x27);
DEFINE_SFR(__pgpu_type, __pgpu, 0x29);
DEFINE_SFR(__pg_type, __pg, 0x2a);
DEFINE_SFR(__pgc_type, __pgc, 0x2b);
DEFINE_SFR(__phpu_type, __phpu, 0x2d);
DEFINE_SFR(__ph_type, __ph, 0x2e);
DEFINE_SFR(__phc_type, __phc, 0x2f);
DEFINE_SFR(__intc0_type, __intc0, 0x30);
DEFINE_SFR(__intc1_type, __intc1, 0x31);
DEFINE_SFR(__intc2_type, __intc2, 0x32);
DEFINE_SFR(__intc3_type, __intc3, 0x33);
DEFINE_SFR(__mfi0_type, __mfi0, 0x34);
DEFINE_SFR(__mfi1_type, __mfi1, 0x35);
DEFINE_SFR(__mfi2_type, __mfi2, 0x36);
DEFINE_SFR(__mfi3_type, __mfi3, 0x37);
DEFINE_SFR(__mfi4_type, __mfi4, 0x38);
DEFINE_SFR(__integ_type, __integ, 0x39);
DEFINE_SFR(__smod_type, __smod, 0x3a);
DEFINE_SFR(__smod1_type, __smod1, 0x3b);
DEFINE_SFR(__lvrc_type, __lvrc, 0x3c);
DEFINE_SFR(__lvdc_type, __lvdc, 0x3d);
DEFINE_SFR(__wdtc_type, __wdtc, 0x3e);
DEFINE_SFR(__smod2_type, __smod2, 0x3f);
DEFINE_SFR(__sfr_byte, __eea, 0x41);
DEFINE_SFR(__sfr_byte, __eed, 0x42);
DEFINE_SFR(__cp0c_type, __cp0c, 0x46);
DEFINE_SFR(__cp1c_type, __cp1c, 0x47);
DEFINE_SFR(__tm1c0_type, __tm1c0, 0x48);
DEFINE_SFR(__tm1c1_type, __tm1c1, 0x49);
DEFINE_SFR(__tm1c2_type, __tm1c2, 0x4a);
DEFINE_SFR(__sfr_byte, __tm1dl, 0x4b);
DEFINE_SFR(__sfr_byte, __tm1dh, 0x4c);
DEFINE_SFR(__sfr_byte, __tm1al, 0x4d);
DEFINE_SFR(__sfr_byte, __tm1ah, 0x4e);
DEFINE_SFR(__sfr_byte, __tm1bl, 0x4f);
DEFINE_SFR(__sfr_byte, __tm1bh, 0x50);
DEFINE_SFR(__tm2c0_type, __tm2c0, 0x51);
DEFINE_SFR(__tm2c1_type, __tm2c1, 0x52);
DEFINE_SFR(__sfr_byte, __tm2dl, 0x53);
DEFINE_SFR(__sfr_byte, __tm2dh, 0x54);
DEFINE_SFR(__sfr_byte, __tm2al, 0x55);
DEFINE_SFR(__sfr_byte, __tm2ah, 0x56);
DEFINE_SFR(__sfr_byte, __tm2rp, 0x57);
DEFINE_SFR(__tm3c0_type, __tm3c0, 0x58);
DEFINE_SFR(__tm3c1_type, __tm3c1, 0x59);
DEFINE_SFR(__sfr_byte, __tm3dl, 0x5a);
DEFINE_SFR(__sfr_byte, __tm3dh, 0x5b);
DEFINE_SFR(__sfr_byte, __tm3al, 0x5c);
DEFINE_SFR(__sfr_byte, __tm3ah, 0x5d);
DEFINE_SFR(__tm0c0_type, __tm0c0, 0x5e);
DEFINE_SFR(__tm0c1_type, __tm0c1, 0x5f);
DEFINE_SFR(__sfr_byte, __tm0dl, 0x60);
DEFINE_SFR(__sfr_byte, __tm0dh, 0x61);
DEFINE_SFR(__sfr_byte, __tm0al, 0x62);
DEFINE_SFR(__sfr_byte, __tm0ah, 0x63);
DEFINE_SFR(__psc0_type, __psc0, 0x64);
DEFINE_SFR(__tbc0_type, __tbc0, 0x65);
DEFINE_SFR(__tbc1_type, __tbc1, 0x66);
DEFINE_SFR(__psc1_type, __psc1, 0x67);
DEFINE_SFR(__adcr0_type, __adcr0, 0x68);
DEFINE_SFR(__adcr1_type, __adcr1, 0x69);
DEFINE_SFR(__sfr_byte, __adrl, 0x6a);
DEFINE_SFR(__sfr_byte, __adrh, 0x6b);
DEFINE_SFR(__simc0_type, __simc0, 0x6c);
DEFINE_SFR(__simc1_type, __simc1, 0x6d);
DEFINE_SFR(__sfr_byte, __simd, 0x6e);
DEFINE_SFR(__simc2_type, __simc2, 0x6f);
DEFINE_SFR(__sima_type, __sima, 0x6f);
DEFINE_SFR(__i2ctoc_type, __i2ctoc, 0x70);
DEFINE_SFR(__spiac0_type, __spiac0, 0x71);
DEFINE_SFR(__spiac1_type, __spiac1, 0x72);
DEFINE_SFR(__sfr_byte, __spiad, 0x73);
DEFINE_SFR(__farl_type, __farl, 0x74);
DEFINE_SFR(__farh_type, __farh, 0x75);
DEFINE_SFR(__sfr_byte, __fd0l, 0x76);
DEFINE_SFR(__sfr_byte, __fd0h, 0x77);
DEFINE_SFR(__sfr_byte, __fd1l, 0x78);
DEFINE_SFR(__sfr_byte, __fd1h, 0x79);
DEFINE_SFR(__sfr_byte, __fd2l, 0x7a);
DEFINE_SFR(__sfr_byte, __fd2h, 0x7b);
DEFINE_SFR(__sfr_byte, __fd3l, 0x7c);
DEFINE_SFR(__sfr_byte, __fd3h, 0x7d);
DEFINE_SFR(__tbc2_type, __tbc2, 0x7e);
DEFINE_SFR(__scomc_type, __scomc, 0x7f);
DEFINE_SFR(__eec_type, __eec, 0x140);
DEFINE_SFR(__fc0_type, __fc0, 0x143);
DEFINE_SFR(__sfr_byte, __fc1, 0x144);
DEFINE_SFR(__fc2_type, __fc2, 0x145);
DEFINE_SFR(__ifs0_type, __ifs0, 0x148);
DEFINE_SFR(__ifs1_type, __ifs1, 0x149);
DEFINE_SFR(__ifs2_type, __ifs2, 0x14a);
DEFINE_SFR(__ifs3_type, __ifs3, 0x14b);
DEFINE_SFR(__ifs4_type, __ifs4, 0x14c);
DEFINE_SFR(__ifs5_type, __ifs5, 0x14d);
DEFINE_SFR(__tm4c0_type, __tm4c0, 0x150);
DEFINE_SFR(__tm4c1_type, __tm4c1, 0x151);
DEFINE_SFR(__sfr_byte, __tm4dl, 0x152);
DEFINE_SFR(__sfr_byte, __tm4dh, 0x153);
DEFINE_SFR(__sfr_byte, __tm4al, 0x154);
DEFINE_SFR(__sfr_byte, __tm4ah, 0x155);
DEFINE_SFR(__sfr_byte, __tm4rp, 0x156);
DEFINE_SFR(__tm5c0_type, __tm5c0, 0x157);
DEFINE_SFR(__tm5c1_type, __tm5c1, 0x158);
DEFINE_SFR(__sfr_byte, __tm5dl, 0x159);
DEFINE_SFR(__sfr_byte, __tm5dh, 0x15a);
DEFINE_SFR(__sfr_byte, __tm5al, 0x15b);
DEFINE_SFR(__sfr_byte, __tm5ah, 0x15c);
DEFINE_SFR(__sfr_byte, __tm5rp, 0x15d);
DEFINE_SFR(__pas0_type, __pas0, 0x160);
DEFINE_SFR(__pas1_type, __pas1, 0x161);
DEFINE_SFR(__pas2_type, __pas2, 0x162);
DEFINE_SFR(__pas3_type, __pas3, 0x163);
DEFINE_SFR(__pbs2_type, __pbs2, 0x166);
DEFINE_SFR(__pbs3_type, __pbs3, 0x167);
DEFINE_SFR(__pcs0_type, __pcs0, 0x168);
DEFINE_SFR(__pcs1_type, __pcs1, 0x169);
DEFINE_SFR(__pcs2_type, __pcs2, 0x16a);
DEFINE_SFR(__pcs3_type, __pcs3, 0x16b);
DEFINE_SFR(__pds0_type, __pds0, 0x16c);
DEFINE_SFR(__pds1_type, __pds1, 0x16d);
DEFINE_SFR(__pds2_type, __pds2, 0x16e);
DEFINE_SFR(__pds3_type, __pds3, 0x16f);
DEFINE_SFR(__pes0_type, __pes0, 0x170);
DEFINE_SFR(__pes1_type, __pes1, 0x171);
DEFINE_SFR(__pes2_type, __pes2, 0x172);
DEFINE_SFR(__pes3_type, __pes3, 0x173);
DEFINE_SFR(__pfs0_type, __pfs0, 0x174);
DEFINE_SFR(__pgs0_type, __pgs0, 0x178);
DEFINE_SFR(__pgs1_type, __pgs1, 0x179);
DEFINE_SFR(__pgs2_type, __pgs2, 0x17a);
DEFINE_SFR(__pgs3_type, __pgs3, 0x17b);
DEFINE_SFR(__phs0_type, __phs0, 0x17c);
DEFINE_SFR(__phs1_type, __phs1, 0x17d);
DEFINE_SFR(__phs2_type, __phs2, 0x17e);
DEFINE_SFR(__sfr_byte, __iar0, 0x00);
DEFINE_SFR(__sfr_byte, __iar1, 0x02);

#define _iar0     __iar0
#define _iar1     __iar1
#define _mp0      __mp0
#define _mp1l     __mp1l
#define _mp1h     __mp1h
#define _acc      __acc
#define _pcl      __pcl
#define _tblp     __tblp
#define _tblh     __tblh
#define _tbhp     __tbhp
#define _status   __status.byte
#define _bp       __bp.byte
#define _mp2l     __mp2l
#define _mp2h     __mp2h
#define _pawu     __pawu.byte
#define _papu     __papu.byte
#define _pa       __pa.byte
#define _pac      __pac.byte
#define _pbpu     __pbpu.byte
#define _pb       __pb.byte
#define _pbc      __pbc.byte
#define _pcpu     __pcpu.byte
#define _pc       __pc.byte
#define _pcc      __pcc.byte
#define _pdpu     __pdpu.byte
#define _pd       __pd.byte
#define _pdc      __pdc.byte
#define _pepu     __pepu.byte
#define _pe       __pe.byte
#define _pec      __pec.byte
#define _pfpu     __pfpu.byte
#define _pf       __pf.byte
#define _pfc      __pfc.byte
#define _pgpu     __pgpu.byte
#define _pg       __pg.byte
#define _pgc      __pgc.byte
#define _phpu     __phpu.byte
#define _ph       __ph.byte
#define _phc      __phc.byte
#define _intc0    __intc0.byte
#define _intc1    __intc1.byte
#define _intc2    __intc2.byte
#define _intc3    __intc3.byte
#define _mfi0     __mfi0.byte
#define _mfi1     __mfi1.byte
#define _mfi2     __mfi2.byte
#define _mfi3     __mfi3.byte
#define _mfi4     __mfi4.byte
#define _integ    __integ.byte
#define _smod     __smod.byte
#define _smod1    __smod1.byte
#define _lvrc     __lvrc.byte
#define _lvdc     __lvdc.byte
#define _wdtc     __wdtc.byte
#define _smod2    __smod2.byte
#define _eea      __eea
#define _eed      __eed
#define _cp0c     __cp0c.byte
#define _cp1c     __cp1c.byte
#define _tm1c0    __tm1c0.byte
#define _tm1c1    __tm1c1.byte
#define _tm1c2    __tm1c2.byte
#define _tm1dl    __tm1dl
#define _tm1dh    __tm1dh
#define _tm1al    __tm1al
#define _tm1ah    __tm1ah
#define _tm1bl    __tm1bl
#define _tm1bh    __tm1bh
#define _tm2c0    __tm2c0.byte
#define _tm2c1    __tm2c1.byte
#define _tm2dl    __tm2dl
#define _tm2dh    __tm2dh
#define _tm2al    __tm2al
#define _tm2ah    __tm2ah
#define _tm2rp    __tm2rp
#define _tm3c0    __tm3c0.byte
#define _tm3c1    __tm3c1.byte
#define _tm3dl    __tm3dl
#define _tm3dh    __tm3dh
#define _tm3al    __tm3al
#define _tm3ah    __tm3ah
#define _tm0c0    __tm0c0.byte
#define _tm0c1    __tm0c1.byte
#define _tm0dl    __tm0dl
#define _tm0dh    __tm0dh
#define _tm0al    __tm0al
#define _tm0ah    __tm0ah
#define _psc0     __psc0.byte
#define _tbc0     __tbc0.byte
#define _tbc1     __tbc1.byte
#define _psc1     __psc1.byte
#define _adcr0    __adcr0.byte
#define _adcr1    __adcr1.byte
#define _adrl     __adrl
#define _adrh     __adrh
#define _simc0    __simc0.byte
#define _simc1    __simc1.byte
#define _simd     __simd
#define _simc2    __simc2.byte
#define _sima     __sima.byte
#define _i2ctoc   __i2ctoc.byte
#define _spiac0   __spiac0.byte
#define _spiac1   __spiac1.byte
#define _spiad    __spiad
#define _farl     __farl.byte
#define _farh     __farh.byte
#define _fd0l     __fd0l
#define _fd0h     __fd0h
#define _fd1l     __fd1l
#define _fd1h     __fd1h
#define _fd2l     __fd2l
#define _fd2h     __fd2h
#define _fd3l     __fd3l
#define _fd3h     __fd3h
#define _tbc2     __tbc2.byte
#define _scomc    __scomc.byte
#define _eec      __eec.byte
#define _fc0      __fc0.byte
#define _fc1      __fc1
#define _fc2      __fc2.byte
#define _ifs0     __ifs0.byte
#define _ifs1     __ifs1.byte
#define _ifs2     __ifs2.byte
#define _ifs3     __ifs3.byte
#define _ifs4     __ifs4.byte
#define _ifs5     __ifs5.byte
#define _tm4c0    __tm4c0.byte
#define _tm4c1    __tm4c1.byte
#define _tm4dl    __tm4dl
#define _tm4dh    __tm4dh
#define _tm4al    __tm4al
#define _tm4ah    __tm4ah
#define _tm4rp    __tm4rp
#define _tm5c0    __tm5c0.byte
#define _tm5c1    __tm5c1.byte
#define _tm5dl    __tm5dl
#define _tm5dh    __tm5dh
#define _tm5al    __tm5al
#define _tm5ah    __tm5ah
#define _tm5rp    __tm5rp
#define _pas0     __pas0.byte
#define _pas1     __pas1.byte
#define _pas2     __pas2.byte
#define _pas3     __pas3.byte
#define _pbs2     __pbs2.byte
#define _pbs3     __pbs3.byte
#define _pcs0     __pcs0.byte
#define _pcs1     __pcs1.byte
#define _pcs2     __pcs2.byte
#define _pcs3     __pcs3.byte
#define _pds0     __pds0.byte
#define _pds1     __pds1.byte
#define _pds2     __pds2.byte
#define _pds3     __pds3.byte
#define _pes0     __pes0.byte
#define _pes1     __pes1.byte
#define _pes2     __pes2.byte
#define _pes3     __pes3.byte
#define _pfs0     __pfs0.byte
#define _pgs0     __pgs0.byte
#define _pgs1     __pgs1.byte
#define _pgs2     __pgs2.byte
#define _pgs3     __pgs3.byte
#define _phs0     __phs0.byte
#define _phs1     __phs1.byte
#define _phs2     __phs2.byte

#define _c        __status.bits.__c
#define _ac       __status.bits.__ac
#define _z        __status.bits.__z
#define _ov       __status.bits.__ov
#define _pdf      __status.bits.__pdf
#define _to       __status.bits.__to
#define _cz       __status.bits.__cz
#define _sc       __status.bits.__sc
#define _bp0      __bp.bits.__bp0
#define _bp1      __bp.bits.__bp1
#define _pawu0    __pawu.bits.__pawu0
#define _pawu1    __pawu.bits.__pawu1
#define _pawu2    __pawu.bits.__pawu2
#define _pawu3    __pawu.bits.__pawu3
#define _pawu4    __pawu.bits.__pawu4
#define _pawu5    __pawu.bits.__pawu5
#define _pawu6    __pawu.bits.__pawu6
#define _pawu7    __pawu.bits.__pawu7
#define _papu0    __papu.bits.__papu0
#define _papu1    __papu.bits.__papu1
#define _papu2    __papu.bits.__papu2
#define _papu3    __papu.bits.__papu3
#define _papu4    __papu.bits.__papu4
#define _papu5    __papu.bits.__papu5
#define _papu6    __papu.bits.__papu6
#define _papu7    __papu.bits.__papu7
#define _pa0      __pa.bits.__pa0
#define _pa1      __pa.bits.__pa1
#define _pa2      __pa.bits.__pa2
#define _pa3      __pa.bits.__pa3
#define _pa4      __pa.bits.__pa4
#define _pa5      __pa.bits.__pa5
#define _pa6      __pa.bits.__pa6
#define _pa7      __pa.bits.__pa7
#define _pac0     __pac.bits.__pac0
#define _pac1     __pac.bits.__pac1
#define _pac2     __pac.bits.__pac2
#define _pac3     __pac.bits.__pac3
#define _pac4     __pac.bits.__pac4
#define _pac5     __pac.bits.__pac5
#define _pac6     __pac.bits.__pac6
#define _pac7     __pac.bits.__pac7
#define _pbpu0    __pbpu.bits.__pbpu0
#define _pbpu1    __pbpu.bits.__pbpu1
#define _pbpu2    __pbpu.bits.__pbpu2
#define _pbpu3    __pbpu.bits.__pbpu3
#define _pbpu4    __pbpu.bits.__pbpu4
#define _pbpu5    __pbpu.bits.__pbpu5
#define _pbpu6    __pbpu.bits.__pbpu6
#define _pbpu7    __pbpu.bits.__pbpu7
#define _pb0      __pb.bits.__pb0
#define _pb1      __pb.bits.__pb1
#define _pb2      __pb.bits.__pb2
#define _pb3      __pb.bits.__pb3
#define _pb4      __pb.bits.__pb4
#define _pb5      __pb.bits.__pb5
#define _pb6      __pb.bits.__pb6
#define _pb7      __pb.bits.__pb7
#define _pbc0     __pbc.bits.__pbc0
#define _pbc1     __pbc.bits.__pbc1
#define _pbc2     __pbc.bits.__pbc2
#define _pbc3     __pbc.bits.__pbc3
#define _pbc4     __pbc.bits.__pbc4
#define _pbc5     __pbc.bits.__pbc5
#define _pbc6     __pbc.bits.__pbc6
#define _pbc7     __pbc.bits.__pbc7
#define _pcpu0    __pcpu.bits.__pcpu0
#define _pcpu1    __pcpu.bits.__pcpu1
#define _pcpu2    __pcpu.bits.__pcpu2
#define _pcpu3    __pcpu.bits.__pcpu3
#define _pcpu4    __pcpu.bits.__pcpu4
#define _pcpu5    __pcpu.bits.__pcpu5
#define _pcpu6    __pcpu.bits.__pcpu6
#define _pcpu7    __pcpu.bits.__pcpu7
#define _pc0      __pc.bits.__pc0
#define _pc1      __pc.bits.__pc1
#define _pc2      __pc.bits.__pc2
#define _pc3      __pc.bits.__pc3
#define _pc4      __pc.bits.__pc4
#define _pc5      __pc.bits.__pc5
#define _pc6      __pc.bits.__pc6
#define _pc7      __pc.bits.__pc7
#define _pcc0     __pcc.bits.__pcc0
#define _pcc1     __pcc.bits.__pcc1
#define _pcc2     __pcc.bits.__pcc2
#define _pcc3     __pcc.bits.__pcc3
#define _pcc4     __pcc.bits.__pcc4
#define _pcc5     __pcc.bits.__pcc5
#define _pcc6     __pcc.bits.__pcc6
#define _pcc7     __pcc.bits.__pcc7
#define _pdpu0    __pdpu.bits.__pdpu0
#define _pdpu1    __pdpu.bits.__pdpu1
#define _pdpu2    __pdpu.bits.__pdpu2
#define _pdpu3    __pdpu.bits.__pdpu3
#define _pdpu4    __pdpu.bits.__pdpu4
#define _pdpu5    __pdpu.bits.__pdpu5
#define _pdpu6    __pdpu.bits.__pdpu6
#define _pdpu7    __pdpu.bits.__pdpu7
#define _pd0      __pd.bits.__pd0
#define _pd1      __pd.bits.__pd1
#define _pd2      __pd.bits.__pd2
#define _pd3      __pd.bits.__pd3
#define _pd4      __pd.bits.__pd4
#define _pd5      __pd.bits.__pd5
#define _pd6      __pd.bits.__pd6
#define _pd7      __pd.bits.__pd7
#define _pdc0     __pdc.bits.__pdc0
#define _pdc1     __pdc.bits.__pdc1
#define _pdc2     __pdc.bits.__pdc2
#define _pdc3     __pdc.bits.__pdc3
#define _pdc4     __pdc.bits.__pdc4
#define _pdc5     __pdc.bits.__pdc5
#define _pdc6     __pdc.bits.__pdc6
#define _pdc7     __pdc.bits.__pdc7
#define _pepu0    __pepu.bits.__pepu0
#define _pepu1    __pepu.bits.__pepu1
#define _pepu2    __pepu.bits.__pepu2
#define _pepu3    __pepu.bits.__pepu3
#define _pepu4    __pepu.bits.__pepu4
#define _pepu5    __pepu.bits.__pepu5
#define _pepu6    __pepu.bits.__pepu6
#define _pepu7    __pepu.bits.__pepu7
#define _pe0      __pe.bits.__pe0
#define _pe1      __pe.bits.__pe1
#define _pe2      __pe.bits.__pe2
#define _pe3      __pe.bits.__pe3
#define _pe4      __pe.bits.__pe4
#define _pe5      __pe.bits.__pe5
#define _pe6      __pe.bits.__pe6
#define _pe7      __pe.bits.__pe7
#define _pec0     __pec.bits.__pec0
#define _pec1     __pec.bits.__pec1
#define _pec2     __pec.bits.__pec2
#define _pec3     __pec.bits.__pec3
#define _pec4     __pec.bits.__pec4
#define _pec5     __pec.bits.__pec5
#define _pec6     __pec.bits.__pec6
#define _pec7     __pec.bits.__pec7
#define _pfpu0    __pfpu.bits.__pfpu0
#define _pfpu1    __pfpu.bits.__pfpu1
#define _pfpu2    __pfpu.bits.__pfpu2
#define _pfpu3    __pfpu.bits.__pfpu3
#define _pfpu4    __pfpu.bits.__pfpu4
#define _pfpu5    __pfpu.bits.__pfpu5
#define _pfpu6    __pfpu.bits.__pfpu6
#define _pf0      __pf.bits.__pf0
#define _pf1      __pf.bits.__pf1
#define _pf2      __pf.bits.__pf2
#define _pf3      __pf.bits.__pf3
#define _pf4      __pf.bits.__pf4
#define _pf5      __pf.bits.__pf5
#define _pf6      __pf.bits.__pf6
#define _pfc0     __pfc.bits.__pfc0
#define _pfc1     __pfc.bits.__pfc1
#define _pfc2     __pfc.bits.__pfc2
#define _pfc3     __pfc.bits.__pfc3
#define _pfc4     __pfc.bits.__pfc4
#define _pfc5     __pfc.bits.__pfc5
#define _pfc6     __pfc.bits.__pfc6
#define _pgpu0    __pgpu.bits.__pgpu0
#define _pgpu1    __pgpu.bits.__pgpu1
#define _pgpu2    __pgpu.bits.__pgpu2
#define _pgpu3    __pgpu.bits.__pgpu3
#define _pgpu4    __pgpu.bits.__pgpu4
#define _pgpu5    __pgpu.bits.__pgpu5
#define _pgpu6    __pgpu.bits.__pgpu6
#define _pgpu7    __pgpu.bits.__pgpu7
#define _pg0      __pg.bits.__pg0
#define _pg1      __pg.bits.__pg1
#define _pg2      __pg.bits.__pg2
#define _pg3      __pg.bits.__pg3
#define _pg4      __pg.bits.__pg4
#define _pg5      __pg.bits.__pg5
#define _pg6      __pg.bits.__pg6
#define _pg7      __pg.bits.__pg7
#define _pgc0     __pgc.bits.__pgc0
#define _pgc1     __pgc.bits.__pgc1
#define _pgc2     __pgc.bits.__pgc2
#define _pgc3     __pgc.bits.__pgc3
#define _pgc4     __pgc.bits.__pgc4
#define _pgc5     __pgc.bits.__pgc5
#define _pgc6     __pgc.bits.__pgc6
#define _pgc7     __pgc.bits.__pgc7
#define _phpu0    __phpu.bits.__phpu0
#define _phpu1    __phpu.bits.__phpu1
#define _phpu2    __phpu.bits.__phpu2
#define _phpu3    __phpu.bits.__phpu3
#define _phpu4    __phpu.bits.__phpu4
#define _phpu5    __phpu.bits.__phpu5
#define _ph0      __ph.bits.__ph0
#define _ph1      __ph.bits.__ph1
#define _ph2      __ph.bits.__ph2
#define _ph3      __ph.bits.__ph3
#define _ph4      __ph.bits.__ph4
#define _ph5      __ph.bits.__ph5
#define _phc0     __phc.bits.__phc0
#define _phc1     __phc.bits.__phc1
#define _phc2     __phc.bits.__phc2
#define _phc3     __phc.bits.__phc3
#define _phc4     __phc.bits.__phc4
#define _phc5     __phc.bits.__phc5
#define _emi      __intc0.bits.__emi
#define _int0e    __intc0.bits.__int0e
#define _int1e    __intc0.bits.__int1e
#define _cp0e     __intc0.bits.__cp0e
#define _int0f    __intc0.bits.__int0f
#define _int1f    __intc0.bits.__int1f
#define _cp0f     __intc0.bits.__cp0f
#define _cp1e     __intc1.bits.__cp1e
#define _mf0e     __intc1.bits.__mf0e
#define _mf1e     __intc1.bits.__mf1e
#define _ade      __intc1.bits.__ade
#define _cp1f     __intc1.bits.__cp1f
#define _mf0f     __intc1.bits.__mf0f
#define _mf1f     __intc1.bits.__mf1f
#define _adf      __intc1.bits.__adf
#define _mf2e     __intc2.bits.__mf2e
#define _tb0e     __intc2.bits.__tb0e
#define _tb1e     __intc2.bits.__tb1e
#define _mf3e     __intc2.bits.__mf3e
#define _mf2f     __intc2.bits.__mf2f
#define _tb0f     __intc2.bits.__tb0f
#define _tb1f     __intc2.bits.__tb1f
#define _mf3f     __intc2.bits.__mf3f
#define _int2e    __intc3.bits.__int2e
#define _int3e    __intc3.bits.__int3e
#define _mf4e     __intc3.bits.__mf4e
#define _int2f    __intc3.bits.__int2f
#define _int3f    __intc3.bits.__int3f
#define _mf4f     __intc3.bits.__mf4f
#define _t0pe     __mfi0.bits.__t0pe
#define _t0ae     __mfi0.bits.__t0ae
#define _t2pe     __mfi0.bits.__t2pe
#define _t2ae     __mfi0.bits.__t2ae
#define _t0pf     __mfi0.bits.__t0pf
#define _t0af     __mfi0.bits.__t0af
#define _t2pf     __mfi0.bits.__t2pf
#define _t2af     __mfi0.bits.__t2af
#define _t1pe     __mfi1.bits.__t1pe
#define _t1ae     __mfi1.bits.__t1ae
#define _t1be     __mfi1.bits.__t1be
#define _t1pf     __mfi1.bits.__t1pf
#define _t1af     __mfi1.bits.__t1af
#define _t1bf     __mfi1.bits.__t1bf
#define _xpe      __mfi2.bits.__xpe
#define _t3pe     __mfi2.bits.__t3pe
#define _t3ae     __mfi2.bits.__t3ae
#define _sime     __mfi2.bits.__sime
#define _xpf      __mfi2.bits.__xpf
#define _t3pf     __mfi2.bits.__t3pf
#define _t3af     __mfi2.bits.__t3af
#define _simf     __mfi2.bits.__simf
#define _lve      __mfi3.bits.__lve
#define _dee      __mfi3.bits.__dee
#define _spiae    __mfi3.bits.__spiae
#define _lvf      __mfi3.bits.__lvf
#define _def      __mfi3.bits.__def
#define _spiaf    __mfi3.bits.__spiaf
#define _t4pe     __mfi4.bits.__t4pe
#define _t4ae     __mfi4.bits.__t4ae
#define _t5pe     __mfi4.bits.__t5pe
#define _t5ae     __mfi4.bits.__t5ae
#define _t4pf     __mfi4.bits.__t4pf
#define _t4af     __mfi4.bits.__t4af
#define _t5pf     __mfi4.bits.__t5pf
#define _t5af     __mfi4.bits.__t5af
#define _int0s0   __integ.bits.__int0s0
#define _int0s1   __integ.bits.__int0s1
#define _int1s0   __integ.bits.__int1s0
#define _int1s1   __integ.bits.__int1s1
#define _int2s0   __integ.bits.__int2s0
#define _int2s1   __integ.bits.__int2s1
#define _int3s0   __integ.bits.__int3s0
#define _int3s1   __integ.bits.__int3s1
#define _hlclk    __smod.bits.__hlclk
#define _idlen    __smod.bits.__idlen
#define _hto      __smod.bits.__hto
#define _lto      __smod.bits.__lto
#define _fsten    __smod.bits.__fsten
#define _cks0     __smod.bits.__cks0
#define _cks1     __smod.bits.__cks1
#define _cks2     __smod.bits.__cks2
#define _wrf      __smod1.bits.__wrf
#define _lrf      __smod1.bits.__lrf
#define _lvrf     __smod1.bits.__lvrf
#define _fsyson   __smod1.bits.__fsyson
#define _lvs0     __lvrc.bits.__lvs0
#define _lvs1     __lvrc.bits.__lvs1
#define _lvs2     __lvrc.bits.__lvs2
#define _lvs3     __lvrc.bits.__lvs3
#define _lvs4     __lvrc.bits.__lvs4
#define _lvs5     __lvrc.bits.__lvs5
#define _lvs6     __lvrc.bits.__lvs6
#define _lvs7     __lvrc.bits.__lvs7
#define _vlvd0    __lvdc.bits.__vlvd0
#define _vlvd1    __lvdc.bits.__vlvd1
#define _vlvd2    __lvdc.bits.__vlvd2
#define _lvden    __lvdc.bits.__lvden
#define _lvdo     __lvdc.bits.__lvdo
#define _ws0      __wdtc.bits.__ws0
#define _ws1      __wdtc.bits.__ws1
#define _ws2      __wdtc.bits.__ws2
#define _we0      __wdtc.bits.__we0
#define _we1      __wdtc.bits.__we1
#define _we2      __wdtc.bits.__we2
#define _we3      __wdtc.bits.__we3
#define _we4      __wdtc.bits.__we4
#define _lxtlp    __smod2.bits.__lxtlp
#define _c0hyen   __cp0c.bits.__c0hyen
#define _c0out    __cp0c.bits.__c0out
#define _c0pol    __cp0c.bits.__c0pol
#define _c0en     __cp0c.bits.__c0en
#define _c1hyen   __cp1c.bits.__c1hyen
#define _c1out    __cp1c.bits.__c1out
#define _c1pol    __cp1c.bits.__c1pol
#define _c1en     __cp1c.bits.__c1en
#define _t1rp0    __tm1c0.bits.__t1rp0
#define _t1rp1    __tm1c0.bits.__t1rp1
#define _t1rp2    __tm1c0.bits.__t1rp2
#define _t1on     __tm1c0.bits.__t1on
#define _t1ck0    __tm1c0.bits.__t1ck0
#define _t1ck1    __tm1c0.bits.__t1ck1
#define _t1ck2    __tm1c0.bits.__t1ck2
#define _t1pau    __tm1c0.bits.__t1pau
#define _t1cclr   __tm1c1.bits.__t1cclr
#define _t1cdn    __tm1c1.bits.__t1cdn
#define _t1apol   __tm1c1.bits.__t1apol
#define _t1aoc    __tm1c1.bits.__t1aoc
#define _t1aio0   __tm1c1.bits.__t1aio0
#define _t1aio1   __tm1c1.bits.__t1aio1
#define _t1am0    __tm1c1.bits.__t1am0
#define _t1am1    __tm1c1.bits.__t1am1
#define _t1pwm0   __tm1c2.bits.__t1pwm0
#define _t1pwm1   __tm1c2.bits.__t1pwm1
#define _t1bpol   __tm1c2.bits.__t1bpol
#define _t1boc    __tm1c2.bits.__t1boc
#define _t1bio0   __tm1c2.bits.__t1bio0
#define _t1bio1   __tm1c2.bits.__t1bio1
#define _t1bm0    __tm1c2.bits.__t1bm0
#define _t1bm1    __tm1c2.bits.__t1bm1
#define _t2on     __tm2c0.bits.__t2on
#define _t2ck0    __tm2c0.bits.__t2ck0
#define _t2ck1    __tm2c0.bits.__t2ck1
#define _t2ck2    __tm2c0.bits.__t2ck2
#define _t2pau    __tm2c0.bits.__t2pau
#define _t2cclr   __tm2c1.bits.__t2cclr
#define _t2dpx    __tm2c1.bits.__t2dpx
#define _t2pol    __tm2c1.bits.__t2pol
#define _t2oc     __tm2c1.bits.__t2oc
#define _t2io0    __tm2c1.bits.__t2io0
#define _t2io1    __tm2c1.bits.__t2io1
#define _t2m0     __tm2c1.bits.__t2m0
#define _t2m1     __tm2c1.bits.__t2m1
#define _t3rp0    __tm3c0.bits.__t3rp0
#define _t3rp1    __tm3c0.bits.__t3rp1
#define _t3rp2    __tm3c0.bits.__t3rp2
#define _t3on     __tm3c0.bits.__t3on
#define _t3ck0    __tm3c0.bits.__t3ck0
#define _t3ck1    __tm3c0.bits.__t3ck1
#define _t3ck2    __tm3c0.bits.__t3ck2
#define _t3pau    __tm3c0.bits.__t3pau
#define _t3cclr   __tm3c1.bits.__t3cclr
#define _t3dpx    __tm3c1.bits.__t3dpx
#define _t3pol    __tm3c1.bits.__t3pol
#define _t3oc     __tm3c1.bits.__t3oc
#define _t3io0    __tm3c1.bits.__t3io0
#define _t3io1    __tm3c1.bits.__t3io1
#define _t3m0     __tm3c1.bits.__t3m0
#define _t3m1     __tm3c1.bits.__t3m1
#define _t0rp0    __tm0c0.bits.__t0rp0
#define _t0rp1    __tm0c0.bits.__t0rp1
#define _t0rp2    __tm0c0.bits.__t0rp2
#define _t0on     __tm0c0.bits.__t0on
#define _t0ck0    __tm0c0.bits.__t0ck0
#define _t0ck1    __tm0c0.bits.__t0ck1
#define _t0ck2    __tm0c0.bits.__t0ck2
#define _t0pau    __tm0c0.bits.__t0pau
#define _t0cclr   __tm0c1.bits.__t0cclr
#define _t0dpx    __tm0c1.bits.__t0dpx
#define _t0pol    __tm0c1.bits.__t0pol
#define _t0oc     __tm0c1.bits.__t0oc
#define _t0io0    __tm0c1.bits.__t0io0
#define _t0io1    __tm0c1.bits.__t0io1
#define _t0m0     __tm0c1.bits.__t0m0
#define _t0m1     __tm0c1.bits.__t0m1
#define _clks00   __psc0.bits.__clks00
#define _clks01   __psc0.bits.__clks01
#define _tb00     __tbc0.bits.__tb00
#define _tb01     __tbc0.bits.__tb01
#define _tb02     __tbc0.bits.__tb02
#define _tb0on    __tbc0.bits.__tb0on
#define _tb10     __tbc1.bits.__tb10
#define _tb11     __tbc1.bits.__tb11
#define _tb12     __tbc1.bits.__tb12
#define _tb1on    __tbc1.bits.__tb1on
#define _clks10   __psc1.bits.__clks10
#define _clks11   __psc1.bits.__clks11
#define _acs0     __adcr0.bits.__acs0
#define _acs1     __adcr0.bits.__acs1
#define _acs2     __adcr0.bits.__acs2
#define _acs3     __adcr0.bits.__acs3
#define _acs4     __adcr0.bits.__acs4
#define _adoff    __adcr0.bits.__adoff
#define _eocb     __adcr0.bits.__eocb
#define _start    __adcr0.bits.__start
#define _adck0    __adcr1.bits.__adck0
#define _adck1    __adcr1.bits.__adck1
#define _adck2    __adcr1.bits.__adck2
#define _vrefs    __adcr1.bits.__vrefs
#define _adrfs    __adcr1.bits.__adrfs
#define _vbgen    __adcr1.bits.__vbgen
#define _simen    __simc0.bits.__simen
#define _simdeb0  __simc0.bits.__simdeb0
#define _simdeb1  __simc0.bits.__simdeb1
#define _sim0     __simc0.bits.__sim0
#define _sim1     __simc0.bits.__sim1
#define _sim2     __simc0.bits.__sim2
#define _rxak     __simc1.bits.__rxak
#define _iamwu    __simc1.bits.__iamwu
#define _srw      __simc1.bits.__srw
#define _txak     __simc1.bits.__txak
#define _htx      __simc1.bits.__htx
#define _hbb      __simc1.bits.__hbb
#define _haas     __simc1.bits.__haas
#define _hcf      __simc1.bits.__hcf
#define _trf      __simc2.bits.__trf
#define _wcol     __simc2.bits.__wcol
#define _csen     __simc2.bits.__csen
#define _mls      __simc2.bits.__mls
#define _ckeg     __simc2.bits.__ckeg
#define _ckpolb   __simc2.bits.__ckpolb
#define _iica0    __sima.bits.__iica0
#define _iica1    __sima.bits.__iica1
#define _iica2    __sima.bits.__iica2
#define _iica3    __sima.bits.__iica3
#define _iica4    __sima.bits.__iica4
#define _iica5    __sima.bits.__iica5
#define _iica6    __sima.bits.__iica6
#define _i2ctos0  __i2ctoc.bits.__i2ctos0
#define _i2ctos1  __i2ctoc.bits.__i2ctos1
#define _i2ctos2  __i2ctoc.bits.__i2ctos2
#define _i2ctos3  __i2ctoc.bits.__i2ctos3
#define _i2ctos4  __i2ctoc.bits.__i2ctos4
#define _i2ctos5  __i2ctoc.bits.__i2ctos5
#define _i2ctof   __i2ctoc.bits.__i2ctof
#define _i2ctoen  __i2ctoc.bits.__i2ctoen
#define _spiaen   __spiac0.bits.__spiaen
#define _saspi0   __spiac0.bits.__saspi0
#define _saspi1   __spiac0.bits.__saspi1
#define _saspi2   __spiac0.bits.__saspi2
#define _satrf    __spiac1.bits.__satrf
#define _sawcol   __spiac1.bits.__sawcol
#define _sacsen   __spiac1.bits.__sacsen
#define _samls    __spiac1.bits.__samls
#define _sackeg   __spiac1.bits.__sackeg
#define _sackpol  __spiac1.bits.__sackpol
#define _a0       __farl.bits.__a0
#define _a1       __farl.bits.__a1
#define _a2       __farl.bits.__a2
#define _a3       __farl.bits.__a3
#define _a4       __farl.bits.__a4
#define _a5       __farl.bits.__a5
#define _a6       __farl.bits.__a6
#define _a7       __farl.bits.__a7
#define _a8       __farh.bits.__a8
#define _a9       __farh.bits.__a9
#define _a10      __farh.bits.__a10
#define _a11      __farh.bits.__a11
#define _a12      __farh.bits.__a12
#define _a13      __farh.bits.__a13
#define _a14      __farh.bits.__a14
#define _tb20     __tbc2.bits.__tb20
#define _tb21     __tbc2.bits.__tb21
#define _tb22     __tbc2.bits.__tb22
#define _tb2en    __tbc2.bits.__tb2en
#define _scomen   __scomc.bits.__scomen
#define _isel0    __scomc.bits.__isel0
#define _isel1    __scomc.bits.__isel1
#define _rd       __eec.bits.__rd
#define _rden     __eec.bits.__rden
#define _wr       __eec.bits.__wr
#define _wren     __eec.bits.__wren
#define _frd      __fc0.bits.__frd
#define _frden    __fc0.bits.__frden
#define _fwt      __fc0.bits.__fwt
#define _fwpen    __fc0.bits.__fwpen
#define _fmod0    __fc0.bits.__fmod0
#define _fmod1    __fc0.bits.__fmod1
#define _fmod2    __fc0.bits.__fmod2
#define _cfwen    __fc0.bits.__cfwen
#define _clwb     __fc2.bits.__clwb
#define _pintbs0  __ifs0.bits.__pintbs0
#define _pintbs1  __ifs0.bits.__pintbs1
#define _tck0s0   __ifs1.bits.__tck0s0
#define _tck0s1   __ifs1.bits.__tck0s1
#define _tck1s0   __ifs1.bits.__tck1s0
#define _tck1s1   __ifs1.bits.__tck1s1
#define _tck2s0   __ifs1.bits.__tck2s0
#define _tck2s1   __ifs1.bits.__tck2s1
#define _tck3s0   __ifs1.bits.__tck3s0
#define _tck3s1   __ifs1.bits.__tck3s1
#define _tpi1as0  __ifs2.bits.__tpi1as0
#define _tpi1as1  __ifs2.bits.__tpi1as1
#define _tpi1bs0  __ifs2.bits.__tpi1bs0
#define _tpi1bs1  __ifs2.bits.__tpi1bs1
#define _tpi2s0   __ifs2.bits.__tpi2s0
#define _tpi2s1   __ifs2.bits.__tpi2s1
#define _tpi4s0   __ifs3.bits.__tpi4s0
#define _tpi4s1   __ifs3.bits.__tpi4s1
#define _tpi5s0   __ifs3.bits.__tpi5s0
#define _tpi5s1   __ifs3.bits.__tpi5s1
#define _scsbs0   __ifs4.bits.__scsbs0
#define _scsbs1   __ifs4.bits.__scsbs1
#define _scks0    __ifs4.bits.__scks0
#define _scks1    __ifs4.bits.__scks1
#define _sdis0    __ifs4.bits.__sdis0
#define _sdis1    __ifs4.bits.__sdis1
#define _scsbas0  __ifs5.bits.__scsbas0
#define _scsbas1  __ifs5.bits.__scsbas1
#define _sckas0   __ifs5.bits.__sckas0
#define _sckas1   __ifs5.bits.__sckas1
#define _sdias0   __ifs5.bits.__sdias0
#define _sdias1   __ifs5.bits.__sdias1
#define _t4on     __tm4c0.bits.__t4on
#define _t4ck0    __tm4c0.bits.__t4ck0
#define _t4ck1    __tm4c0.bits.__t4ck1
#define _t4ck2    __tm4c0.bits.__t4ck2
#define _t4pau    __tm4c0.bits.__t4pau
#define _t4cclr   __tm4c1.bits.__t4cclr
#define _t4dpx    __tm4c1.bits.__t4dpx
#define _t4pol    __tm4c1.bits.__t4pol
#define _t4oc     __tm4c1.bits.__t4oc
#define _t4io0    __tm4c1.bits.__t4io0
#define _t4io1    __tm4c1.bits.__t4io1
#define _t4m0     __tm4c1.bits.__t4m0
#define _t4m1     __tm4c1.bits.__t4m1
#define _t5on     __tm5c0.bits.__t5on
#define _t5ck0    __tm5c0.bits.__t5ck0
#define _t5ck1    __tm5c0.bits.__t5ck1
#define _t5ck2    __tm5c0.bits.__t5ck2
#define _t5pau    __tm5c0.bits.__t5pau
#define _t5cclr   __tm5c1.bits.__t5cclr
#define _t5dpx    __tm5c1.bits.__t5dpx
#define _t5pol    __tm5c1.bits.__t5pol
#define _t5oc     __tm5c1.bits.__t5oc
#define _t5io0    __tm5c1.bits.__t5io0
#define _t5io1    __tm5c1.bits.__t5io1
#define _t5m0     __tm5c1.bits.__t5m0
#define _t5m1     __tm5c1.bits.__t5m1
#define _pa1s0    __pas0.bits.__pa1s0
#define _pa1s1    __pas0.bits.__pa1s1
#define _pa1s2    __pas0.bits.__pa1s2
#define _pa1s3    __pas0.bits.__pa1s3
#define _pa3s0    __pas1.bits.__pa3s0
#define _pa3s1    __pas1.bits.__pa3s1
#define _pa3s2    __pas1.bits.__pa3s2
#define _pa3s3    __pas1.bits.__pa3s3
#define _pa4s0    __pas2.bits.__pa4s0
#define _pa4s1    __pas2.bits.__pa4s1
#define _pa4s2    __pas2.bits.__pa4s2
#define _pa4s3    __pas2.bits.__pa4s3
#define _pa5s0    __pas2.bits.__pa5s0
#define _pa5s1    __pas2.bits.__pa5s1
#define _pa5s2    __pas2.bits.__pa5s2
#define _pa5s3    __pas2.bits.__pa5s3
#define _pa6s0    __pas3.bits.__pa6s0
#define _pa6s1    __pas3.bits.__pa6s1
#define _pa6s2    __pas3.bits.__pa6s2
#define _pa6s3    __pas3.bits.__pa6s3
#define _pa7s0    __pas3.bits.__pa7s0
#define _pa7s1    __pas3.bits.__pa7s1
#define _pa7s2    __pas3.bits.__pa7s2
#define _pa7s3    __pas3.bits.__pa7s3
#define _pb5s0    __pbs2.bits.__pb5s0
#define _pb5s1    __pbs2.bits.__pb5s1
#define _pb5s2    __pbs2.bits.__pb5s2
#define _pb5s3    __pbs2.bits.__pb5s3
#define _pb6s0    __pbs3.bits.__pb6s0
#define _pb6s1    __pbs3.bits.__pb6s1
#define _pb6s2    __pbs3.bits.__pb6s2
#define _pb6s3    __pbs3.bits.__pb6s3
#define _pb7s0    __pbs3.bits.__pb7s0
#define _pb7s1    __pbs3.bits.__pb7s1
#define _pb7s2    __pbs3.bits.__pb7s2
#define _pb7s3    __pbs3.bits.__pb7s3
#define _pc0s0    __pcs0.bits.__pc0s0
#define _pc0s1    __pcs0.bits.__pc0s1
#define _pc0s2    __pcs0.bits.__pc0s2
#define _pc0s3    __pcs0.bits.__pc0s3
#define _pc1s0    __pcs0.bits.__pc1s0
#define _pc1s1    __pcs0.bits.__pc1s1
#define _pc1s2    __pcs0.bits.__pc1s2
#define _pc1s3    __pcs0.bits.__pc1s3
#define _pc2s0    __pcs1.bits.__pc2s0
#define _pc2s1    __pcs1.bits.__pc2s1
#define _pc2s2    __pcs1.bits.__pc2s2
#define _pc2s3    __pcs1.bits.__pc2s3
#define _pc3s0    __pcs1.bits.__pc3s0
#define _pc3s1    __pcs1.bits.__pc3s1
#define _pc3s2    __pcs1.bits.__pc3s2
#define _pc3s3    __pcs1.bits.__pc3s3
#define _pc4s0    __pcs2.bits.__pc4s0
#define _pc4s1    __pcs2.bits.__pc4s1
#define _pc4s2    __pcs2.bits.__pc4s2
#define _pc4s3    __pcs2.bits.__pc4s3
#define _pc5s0    __pcs2.bits.__pc5s0
#define _pc5s1    __pcs2.bits.__pc5s1
#define _pc5s2    __pcs2.bits.__pc5s2
#define _pc5s3    __pcs2.bits.__pc5s3
#define _pc6s0    __pcs3.bits.__pc6s0
#define _pc6s1    __pcs3.bits.__pc6s1
#define _pc6s2    __pcs3.bits.__pc6s2
#define _pc6s3    __pcs3.bits.__pc6s3
#define _pc7s0    __pcs3.bits.__pc7s0
#define _pc7s1    __pcs3.bits.__pc7s1
#define _pc7s2    __pcs3.bits.__pc7s2
#define _pc7s3    __pcs3.bits.__pc7s3
#define _pd0s0    __pds0.bits.__pd0s0
#define _pd0s1    __pds0.bits.__pd0s1
#define _pd0s2    __pds0.bits.__pd0s2
#define _pd0s3    __pds0.bits.__pd0s3
#define _pd1s0    __pds0.bits.__pd1s0
#define _pd1s1    __pds0.bits.__pd1s1
#define _pd1s2    __pds0.bits.__pd1s2
#define _pd1s3    __pds0.bits.__pd1s3
#define _pd2s0    __pds1.bits.__pd2s0
#define _pd2s1    __pds1.bits.__pd2s1
#define _pd2s2    __pds1.bits.__pd2s2
#define _pd2s3    __pds1.bits.__pd2s3
#define _pd3s0    __pds1.bits.__pd3s0
#define _pd3s1    __pds1.bits.__pd3s1
#define _pd3s2    __pds1.bits.__pd3s2
#define _pd3s3    __pds1.bits.__pd3s3
#define _pd4s0    __pds2.bits.__pd4s0
#define _pd4s1    __pds2.bits.__pd4s1
#define _pd4s2    __pds2.bits.__pd4s2
#define _pd4s3    __pds2.bits.__pd4s3
#define _pd5s0    __pds2.bits.__pd5s0
#define _pd5s1    __pds2.bits.__pd5s1
#define _pd5s2    __pds2.bits.__pd5s2
#define _pd5s3    __pds2.bits.__pd5s3
#define _pd6s0    __pds3.bits.__pd6s0
#define _pd6s1    __pds3.bits.__pd6s1
#define _pd6s2    __pds3.bits.__pd6s2
#define _pd6s3    __pds3.bits.__pd6s3
#define _pd7s0    __pds3.bits.__pd7s0
#define _pd7s1    __pds3.bits.__pd7s1
#define _pd7s2    __pds3.bits.__pd7s2
#define _pd7s3    __pds3.bits.__pd7s3
#define _pe0s0    __pes0.bits.__pe0s0
#define _pe0s1    __pes0.bits.__pe0s1
#define _pe0s2    __pes0.bits.__pe0s2
#define _pe0s3    __pes0.bits.__pe0s3
#define _pe1s0    __pes0.bits.__pe1s0
#define _pe1s1    __pes0.bits.__pe1s1
#define _pe1s2    __pes0.bits.__pe1s2
#define _pe1s3    __pes0.bits.__pe1s3
#define _pe3s0    __pes1.bits.__pe3s0
#define _pe3s1    __pes1.bits.__pe3s1
#define _pe3s2    __pes1.bits.__pe3s2
#define _pe3s3    __pes1.bits.__pe3s3
#define _pe4s0    __pes2.bits.__pe4s0
#define _pe4s1    __pes2.bits.__pe4s1
#define _pe4s2    __pes2.bits.__pe4s2
#define _pe4s3    __pes2.bits.__pe4s3
#define _pe5s0    __pes2.bits.__pe5s0
#define _pe5s1    __pes2.bits.__pe5s1
#define _pe5s2    __pes2.bits.__pe5s2
#define _pe5s3    __pes2.bits.__pe5s3
#define _pe6s0    __pes3.bits.__pe6s0
#define _pe6s1    __pes3.bits.__pe6s1
#define _pe6s2    __pes3.bits.__pe6s2
#define _pe6s3    __pes3.bits.__pe6s3
#define _pe7s0    __pes3.bits.__pe7s0
#define _pe7s1    __pes3.bits.__pe7s1
#define _pe7s2    __pes3.bits.__pe7s2
#define _pe7s3    __pes3.bits.__pe7s3
#define _pf0s0    __pfs0.bits.__pf0s0
#define _pf0s1    __pfs0.bits.__pf0s1
#define _pf0s2    __pfs0.bits.__pf0s2
#define _pf0s3    __pfs0.bits.__pf0s3
#define _pf1s0    __pfs0.bits.__pf1s0
#define _pf1s1    __pfs0.bits.__pf1s1
#define _pf1s2    __pfs0.bits.__pf1s2
#define _pf1s3    __pfs0.bits.__pf1s3
#define _pg0s0    __pgs0.bits.__pg0s0
#define _pg0s1    __pgs0.bits.__pg0s1
#define _pg0s2    __pgs0.bits.__pg0s2
#define _pg0s3    __pgs0.bits.__pg0s3
#define _pg1s0    __pgs0.bits.__pg1s0
#define _pg1s1    __pgs0.bits.__pg1s1
#define _pg1s2    __pgs0.bits.__pg1s2
#define _pg1s3    __pgs0.bits.__pg1s3
#define _pg3s0    __pgs1.bits.__pg3s0
#define _pg3s1    __pgs1.bits.__pg3s1
#define _pg3s2    __pgs1.bits.__pg3s2
#define _pg3s3    __pgs1.bits.__pg3s3
#define _pg4s0    __pgs2.bits.__pg4s0
#define _pg4s1    __pgs2.bits.__pg4s1
#define _pg4s2    __pgs2.bits.__pg4s2
#define _pg4s3    __pgs2.bits.__pg4s3
#define _pg6s0    __pgs3.bits.__pg6s0
#define _pg6s1    __pgs3.bits.__pg6s1
#define _pg6s2    __pgs3.bits.__pg6s2
#define _pg6s3    __pgs3.bits.__pg6s3
#define _pg7s0    __pgs3.bits.__pg7s0
#define _pg7s1    __pgs3.bits.__pg7s1
#define _pg7s2    __pgs3.bits.__pg7s2
#define _pg7s3    __pgs3.bits.__pg7s3
#define _ph0s0    __phs0.bits.__ph0s0
#define _ph0s1    __phs0.bits.__ph0s1
#define _ph0s2    __phs0.bits.__ph0s2
#define _ph0s3    __phs0.bits.__ph0s3
#define _ph1s0    __phs0.bits.__ph1s0
#define _ph1s1    __phs0.bits.__ph1s1
#define _ph1s2    __phs0.bits.__ph1s2
#define _ph1s3    __phs0.bits.__ph1s3
#define _ph2s0    __phs1.bits.__ph2s0
#define _ph2s1    __phs1.bits.__ph2s1
#define _ph2s2    __phs1.bits.__ph2s2
#define _ph2s3    __phs1.bits.__ph2s3
#define _ph3s0    __phs1.bits.__ph3s0
#define _ph3s1    __phs1.bits.__ph3s1
#define _ph3s2    __phs1.bits.__ph3s2
#define _ph3s3    __phs1.bits.__ph3s3
#define _ph5s0    __phs2.bits.__ph5s0
#define _ph5s1    __phs2.bits.__ph5s1
#define _ph5s2    __phs2.bits.__ph5s2
#define _ph5s3    __phs2.bits.__ph5s3

#define ___mkstr(x)                #x
#define __EEPROM_DATA(a, b, c, d, e, f, g, h) \
                         asm("eeprom_data .section 'eeprom'"); \
                         asm("db\t" ___mkstr(a));        \
                         asm("db\t" ___mkstr(b));        \
                         asm("db\t" ___mkstr(c));        \
                         asm("db\t" ___mkstr(d));        \
                         asm("db\t" ___mkstr(e));        \
                         asm("db\t" ___mkstr(f));        \
                         asm("db\t" ___mkstr(g));        \
                         asm("db\t" ___mkstr(h));        

#endif // _HOLTEK_H_
